[[xml]]
= XML Support - Dealing with XML Payloads

Spring Integration's XML support extends the core of Spring Integration with the following components:

* <<xml-transformation,Marshalling Transformer>>
* <<xml-transformation,Unmarshalling Transformer>>
* <<xml-transformation,XSLT Transformer>>
* <<xml-xpath-transformer,XPath Transformer>>
* <<xml-xpath-splitting,XPath Splitter>>
* <<xml-xpath-routing,XPath Router>>
* <<xml-xpath-header-enricher,XPath Header Enricher>>
* <<xml-xpath-filter,XPath Filter>>
* <<xpath-spel-function,#xpath SpEL Function>>
* <<xml-validating-filter,Validating Filter>>

You need to include this dependency into your project:

====
[source, xml, subs="normal", role="primary"]
.Maven
----
<dependency>
    <groupId>org.springframework.integration</groupId>
    <artifactId>spring-integration-xml</artifactId>
    <version>{project-version}</version>
</dependency>
----

[source, groovy, subs="normal", role="secondary"]
.Gradle
----
compile "org.springframework.integration:spring-integration-xml:{project-version}"
----
====

These components make working with XML messages in Spring Integration simpler.
The messaging components work with XML that is represented in a range of formats, including instances of `java.lang.String`, `org.w3c.dom.Document`, and `javax.xml.transform.Source`.
However, where a DOM representation is required (for example, in order to evaluate an XPath expression), the `String` payload is converted into the required type and then converted back to `String`.
Components that require an instance of `DocumentBuilder` create a namespace-aware instance if you do not provide one.
When you require greater control over document creation, you can provide an appropriately configured instance of `DocumentBuilder`.

