description = 'Spring Integration JMS Support'
dependencies {
    api 'org.springframework:spring-jms'
    optionalApi libs.jakarta.jms.api

    testImplementation 'org.apache.artemis:artemis-server'
    testImplementation 'org.apache.artemis:artemis-jakarta-client'
    testImplementation 'org.springframework:spring-oxm'
    testImplementation 'tools.jackson.core:jackson-databind'
    testImplementation 'io.micrometer:micrometer-observation-test'
}
