[[migration-2.0-2.1]]
=== Changes between 2.0 and 2.1

[[x2.1-new-components]]
==== New Components

[[x2.1-new-scripting-support]]
===== JSR-223 Scripting Support

In Spring Integration 2.0, support for http://groovy.codehaus.org/[Groovy] was added.
With Spring Integration 2.1 we expanded support for additional languages substantially by implementing support for http://www.jcp.org/en/jsr/detail?id=223[JSR-223] (Scripting for the Java™ Platform).
Now you have the ability to use any scripting language that supports JSR-223 including:

* Javascript
* Ruby/JRuby
* Python/Jython
* Groovy



For further details please see <<scripting>>.

[[x2.1-new-gemfire-support]]
===== GemFire Support

Spring Integration provides support for http://www.vmware.com/products/application-platform/vfabric-gemfire/overview.html[GemFire] by providing inbound adapters for entry and continuous query events, an outbound adapter to write entries to the cache, and http://static.springsource.org/spring-integration/api/org/springframework/integration/store/MessageStore.html[`MessageStore`] and http://static.springsource.org/spring-integration/api/org/springframework/integration/store/MessageGroupStore.html[`MessageGroupStore`] implementations.
Spring integration leverages the http://www.springsource.org/spring-gemfire[_Spring Gemfire_] project, providing a thin wrapper over its components.

For further details please see <<gemfire>>.

[[x2.1-new-amqp-support]]
===== AMQP Support

Spring Integration 2.1 adds several Channel Adapters for receiving and sending messages using thehttp://www.amqp.org/[_Advanced Message Queuing Protocol_] (AMQP).
Furthermore, Spring Integration also provides a point-to-point Message Channel, as well as a publish/subscribe Message Channel that are backed by AMQP Exchanges and Queues.

For further details please see <<amqp>>.

[[x2.1-new-mongodb-support]]
===== MongoDB Support

As of version 2.1 Spring Integration provides support for http://www.mongodb.org/[MongoDB] by providing a MongoDB-based MessageStore.

For further details please see <<mongodb>>.

[[x2.1-new-redis-support]]
===== Redis Support

As of version 2.1 Spring Integration supports http://redis.io/[Redis], an advanced key-value store, by providing a Redis-based MessageStore as well as Publish-Subscribe Messaging adapters.

For further details please see <<redis>>.

[[x2.1-new-resource-support]]
===== Support for Spring's Resource abstraction

As of version 2.1, we've introduced a new _Resource Inbound Channel Adapter_ that builds upon Spring's Resource abstraction to support greater flexibility across a variety of actual types of underlying resources, such as a file, a URL, or a class path resource.
Therefore, it's similar to but more generic than the _File Inbound Channel Adapter_.

For further details please see <<resource-inbound-channel-adapter>>.

[[x2.1-new-stored-proc-support]]
===== Stored Procedure Components

With Spring Integration 2.1, the `JDBC` Module also provides Stored Procedure support by adding several new components, including inbound/outbound channel adapters and an Outbound Gateway.
The Stored Procedure support leverages Spring'shttp://static.springsource.org/spring/docs/3.0.x/javadoc-api/org/springframework/jdbc/core/simple/SimpleJdbcCall.html[`SimpleJdbcCall`] class and consequently supports stored procedures for:

* Apache Derby
* DB2
* MySQL
* Microsoft SQL Server
* Oracle
* PostgreSQL
* Sybase



The Stored Procedure components also support Sql Functions for the following databases:

* MySQL
* Microsoft SQL Server
* Oracle
* PostgreSQL



For further details please see <<stored-procedures>>.

[[x2.1-new-xpath-filter-support]]
===== XPath and XML Validating Filter

Spring Integration 2.1 provides a new XPath-based Message Filter, that is part of the `XML` module.
The XPath Filter allows you to filter messages using provided XPath Expressions.
Furthermore, documentation was added for the XML Validating Filter.

For more details please see <<xml-xpath-filter>> and <<xml-validating-filter>>.

[[x2.1-new-payload-enricher-support]]
===== Payload Enricher

Since Spring Integration 2.1, the Payload Enricher is provided.
A Payload Enricher defines an endpoint that typically passes ahttp://static.springsource.org/spring-integration/api/org/springframework/integration/Message.html[`Message`] to the exposed request channel and then expects a reply message.
The reply message then becomes the root object for evaluation of expressions to enrich the target payload.

For further details please see <<payload-enricher>>.

[[x2.1-new-ftp-outbound-gateway]]
===== FTP and SFTP Outbound Gateways

Spring Integration 2.1 provides two new Outbound Gateways in order to interact with remote File Transfer Protocol (FTP) or Secure File Transfer Protocol (SFT) servers.
These two gateways allow you to directly execute a limited set of remote commands.

For instance, you can use these Outbound Gateways to list, retrieve and delete remote files and have the Spring Integration message flow continue with the remote server's response.

For further details please see <<ftp-outbound-gateway>> and <<sftp-outbound-gateway>>.

[[x2.1-new-ftp-session-caching]]
===== FTP Session Caching

As of version 2.1, we have exposed more flexibility with regards to session management for remote file adapters (e.g., FTP, SFTP etc).

Specifically, the `cache-sessions` attribute, which is available via the XML namespace support, is now _deprecated_.
Alternatively, we added the `sessionCacheSize` and `sessionWaitTimeout` attributes on the `CachingSessionFactory`.

For further details please see <<ftp-session-caching>> and <<sftp-session-caching>>.

[[x2.1-framework-refactorings]]
==== Framework Refactoring

[[x2.1-router-standardization]]
===== Standardizing Router Configuration

Router parameters have been standardized across all router implementations with Spring Integration 2.1 providing a more consistent user experience.

With Spring Integration 2.1 the `ignore-channel-name-resolution-failures` attribute has been removed in favor of consolidating its behavior with the `resolution-required` attribute.
Also, the `resolution-required` attribute now defaults to `true`.

Starting with Spring Integration 2.1, routers will no longer silently drop any messages, if no default output channel was defined.
This means, that by default routers now require at least one resolved channel (if no `default-output-channel` was set) and by default will throw a `MessageDeliveryException` if no channel was determined (or an attempt to send was not successful).

If, however, you do desire to drop messages silently, simply set `default-output-channel="nullChannel"`.

IMPORTANT: With the standardization of Router parameters and the consolidation of the parameters described above, there is the possibility of breaking older Spring Integration based applications.

For further details please see <<router>>

[[x2.1-schema-updated]]
===== XML Schemas updated to 2.1

Spring Integration 2.1 ships with an updated XML Schema (version 2.1), providing many improvements, e.g.
the Router standardizations discussed above.

From now on, users _must_ always declare the latest XML schema (currently version 2.1).
Alternatively, they can use the version-less schema.
Generally, the best option is to use version-less namespaces, as these will automatically use the latest available version of Spring Integration.

Declaring a version-less Spring Integration namespace:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns:int="http://www.springframework.org/schema/integration"
   xsi:schemaLocation="http://www.springframework.org/schema/integration
           http://www.springframework.org/schema/integration/spring-integration.xsd
           http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans.xsd">
...
</beans>
----

Declaring a Spring Integration namespace using an explicit version:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns:int="http://www.springframework.org/schema/integration"
   xsi:schemaLocation="http://www.springframework.org/schema/integration
           http://www.springframework.org/schema/integration/spring-integration-2.2.xsd
           http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans.xsd">
...
</beans>
----

The old 1.0 and 2.0 schemas are still there, but if an Application Context still references one of those deprecated schemas, the validator will fail on initialization.

[[x2.1-source-control-infrastructure]]
==== Source Control Management and Build Infrastructure

[[x2.1-move-to-github]]
===== Source Code now hosted on Github

Since version 2.0, the Spring Integration project uses http://git-scm.com/[Git] for version control.
In order to increase community visibility even further, the project was moved from SpringSource hosted Git repositories to http://www.github.com/[Github].
The Spring Integration Git repository is located at: https://github.com/spring-projects/spring-integration[spring-integration].

For the project we also improved the process of providing code contributions and we ensure that every commit is peer-reviewed.
In fact, core committers now follow the same process as contributors.
For more details please see:

https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc[Contributing].

[[x2.1-sonar]]
===== Improved Source Code Visibility with Sonar

In an effort to provide better source code visibility and consequently to monitor the quality of Spring Integration's source code, an instance of http://www.sonarsource.org/[Sonar] was setup and metrics are gathered nightly and made available at:

https://sonar.spring.io/dashboard?id=org.springframework.integration%3Aspring-integration%3Amaster[sonar.spring.io].

[[x2.1-new-samples]]
==== New Samples

For the 2.1 release of Spring Integration we also expanded the Spring Integration Samples project and added many new samples, e.g.
samples covering AMQP support, the new payload enricher, a sample illustrating techniques for testing Spring Integration flow fragments, as well as an example for executing Stored Procedures against Oracle.
For details please visit:

https://github.com/spring-projects/spring-integration-samples[spring-integration-samples].
