[[content-enricher]]
=== Content Enricher

[[content-enricher-introduction]]
==== Introduction

At times you may have a requirement to enhance a request with more information than was provided by the target system.
The http://www.eaipatterns.com/DataEnricher.html[Content Enricher] pattern describes various scenarios as well as the component (Enricher), which allows you to address such requirements.

The Spring Integration `Core` module includes 2 enrichers:

* <<header-enricher,Header Enricher>>
* <<payload-enricher,Payload Enricher>>



Furthermore, several _Adapter specific Header Enrichers_ are included as well:

* <<xml-xpath-header-enricher,XPath Header Enricher (XML Module)>>
* <<mail-namespace,Mail Header Enricher (Mail Module)>>
* <<xmpp-message-outbound-channel-adapter,XMPP Header Enricher (XMPP Module)>>



Please go to the adapter specific sections of this reference manual to learn more about those adapters.

For more information regarding expressions support, please see <<spel>>.

[[header-enricher]]
==== Header Enricher

If you only need to add headers to a Message, and they are not dynamically determined by the Message content, then referencing a custom implementation of a Transformer may be overkill.
For that reason, Spring Integration provides support for the _Header Enricher_ pattern.
It is exposed via the `<header-enricher>` element.

[source,xml]
----
<int:header-enricher input-channel="in" output-channel="out">
    <int:header name="foo" value="123"/>
    <int:header name="bar" ref="someBean"/>
</int:header-enricher>
----

The _Header Enricher_ also provides helpful sub-elements to set well-known header names.

[source,xml]
----
<int:header-enricher input-channel="in" output-channel="out">
    <int:error-channel ref="applicationErrorChannel"/>
    <int:reply-channel ref="quoteReplyChannel"/>
    <int:correlation-id value="123"/>
    <int:priority value="HIGHEST"/>
    <routing-slip value="channel1; routingSlipRoutingStrategy; request.headers[myRoutingSlipChannel]"/>
    <int:header name="bar" ref="someBean"/>
</int:header-enricher>
----

In the above configuration you can clearly see that for well-known headers such as `errorChannel`, `correlationId`, `priority`, `replyChannel`, `routing-slip` etc., instead of using generic _<header>_ sub-elements where you would have to provide both header 'name' and 'value', you can use convenient sub-elements to set those values directly.

Starting with _version 4.1_ the _Header Enricher_ provides `routing-slip` sub-element.
See <<routing-slip>> for more information.

*POJO Support*

Often a header value cannot be defined statically and has to be determined dynamically based on some content in the Message.
That is why _Header Enricher_ allows you to also specify a bean reference using the `ref` and `method` attribute.
The specified method will calculate the header value.
Let's look at the following configuration:

[source,xml]
----
<int:header-enricher input-channel="in" output-channel="out">
    <int:header name="foo" method="computeValue" ref="myBean"/>
</int:header-enricher>

<bean id="myBean" class="foo.bar.MyBean"/>
----

[source,java]
----
public class MyBean {

    public String computeValue(String payload){
        return payload.toUpperCase() + "_US";
    }
}
----

You can also configure your POJO as inner bean:

[source,xml]
----
<int:header-enricher  input-channel="inputChannel" output-channel="outputChannel">
    <int:header name="some_header">
        <bean class="org.MyEnricher"/>
    </int:header>
</int:header-enricher>
----

as well as point to a Groovy script:

[source,xml]
----
<int:header-enricher  input-channel="inputChannel" output-channel="outputChannel">
    <int:header name="some_header">
        <int-groovy:script location="org/SampleGroovyHeaderEnricher.groovy"/>
    </int:header>
</int:header-enricher>
----

*SpEL Support*

In Spring Integration 2.0 we have introduced the convenience of the http://docs.spring.io/spring/docs/current/spring-framework-reference/html/expressions.html[Spring Expression Language (SpEL)] to help configure many different components.
The _Header Enricher_ is one of them.
Looking again at the POJO example above, you can see that the computation logic to determine the header value is actually pretty simple.
A natural question would be: "is there a simpler way to accomplish this?".
That is where SpEL shows its true power.

[source,xml]
----
<int:header-enricher input-channel="in" output-channel="out">
    <int:header name="foo" expression="payload.toUpperCase() + '_US'"/>
</int:header-enricher>
----

As you can see, by using SpEL for such simple cases, we no longer have to provide a separate class and configure it in the application context.
All we need is the _expression_ attribute configured with a valid SpEL expression.
The 'payload' and 'headers' variables are bound to the SpEL Evaluation Context, giving you full access to the incoming Message.

===== Configuring a Header Enricher with Java Configuration

The following are some examples of Java Configuration for header enrichers:

[source, java]
----
@Bean
@Transformer(inputChannel = "enrichHeadersChannel", outputChannel = "emailChannel")
public HeaderEnricher enrichHeaders() {
    Map<String, ? extends HeaderValueMessageProcessor<?>> headersToAdd =
            Collections.singletonMap("emailUrl",
                      new StaticHeaderValueMessageProcessor<>(this.imapUrl));
    HeaderEnricher enricher = new HeaderEnricher(headersToAdd);
    return enricher;
}

@Bean
@Transformer(inputChannel="enrichHeadersChannel", outputChannel="emailChannel")
public HeaderEnricher enrichHeaders() {
    Map<String, HeaderValueMessageProcessor<?>> headersToAdd = new HashMap<>();
    headersToAdd.put("emailUrl", new StaticHeaderValueMessageProcessor<String>(this.imapUrl));
    Expression expression = new SpelExpressionParser().parseExpression("payload.from[0].toString()");
    headersToAdd.put("from",
               new ExpressionEvaluatingHeaderValueMessageProcessor<>(expression, String.class));
    HeaderEnricher enricher = new HeaderEnricher(headersToAdd);
    return enricher;
}
----

The first adds a single literal header.
The second adds two headers - a literal header and one based on a SpEL expression.

===== Configuring a Header Enricher with the Java DSL

The following is an example of Java DSL Configuration for a header enricher:

[source, java]
----
@Bean
public IntegrationFlow enrichHeadersInFlow() {
    return f -> f
                ...
                .enrichHeaders(h -> h.header("emailUrl", this.emailUrl)
                                     .headerExpression("from", "payload.from[0].toString()"))
                .handle(...);
}
----

[[header-channel-registry]]
===== Header Channel Registry

Starting with _Spring Integration 3.0_, a new sub-element `<int:header-channels-to-string/>` is available; it has no attributes.
This converts existing `replyChannel` and `errorChannel` headers (when they are a `MessageChannel`) to a String and stores the channel(s) in a registry for later resolution when it is time to send a reply, or handle an error.
This is useful for cases where the headers might be lost; for example when serializing a message into a message store or when transporting the message over JMS.
If the header does not already exist, or it is not a `MessageChannel`, no changes are made.

Use of this functionality requires the presence of a `HeaderChannelRegistry` bean.
By default, the framework creates a `DefaultHeaderChannelRegistry` with the default expiry (60 seconds).
Channels are removed from the registry after this time.
To change this, simply define a bean with id `integrationHeaderChannelRegistry` and configure the required default delay using a constructor argument (milliseconds).

Since _version 4.1_, you can set a property `removeOnGet` to `true` on the `<bean/>` definition, and the mapping entry will be removed immediately on first use.
This might be useful in a high-volume environment and when the channel is only used once, rather than waiting for the reaper to remove it.

The `HeaderChannelRegistry` has a `size()` method to determine the current size of the registry.
The `runReaper()` method cancels the current scheduled task and runs the reaper immediately; the task is then scheduled to run again based on the current delay.
These methods can be invoked directly by getting a reference to the registry, or you can send a message with, for example, the following content to a control bus:

[source]
----
"@integrationHeaderChannelRegistry.runReaper()"
----

This sub-element is a convenience only, and is the equivalent of specifying:

[source,xml]
----
<int:reply-channel
    expression="@integrationHeaderChannelRegistry.channelToChannelName(headers.replyChannel)"
    overwrite="true" />
<int:error-channel
    expression="@integrationHeaderChannelRegistry.channelToChannelName(headers.errorChannel)"
    overwrite="true" />
----

Starting with _version 4.1_, you can now override the registry's configured reaper delay, so the the channel mapping is retained for at least the specified time, regardless of the reaper delay:

[source,xml]
----
<int:header-enricher input-channel="inputTtl" output-channel="next">
    <int:header-channels-to-string time-to-live-expression="120000" />
</int:header-enricher>

<int:header-enricher input-channel="inputCustomTtl" output-channel="next">
    <int:header-channels-to-string
        time-to-live-expression="headers['channelTTL'] ?: 120000" />
</int:header-enricher>
----

In the first case, the time to live for every header channel mapping will be 2 minutes; in the second case, the time to live is specified in the message header and uses an elvis operator to use 2 minutes if there is no header.

[[payload-enricher]]
==== Payload Enricher

In certain situations the Header Enricher, as discussed above, may not be sufficient and payloads themselves may have to be enriched with additional information.
For example, order messages that enter the Spring Integration messaging system have to look up the order's customer based on the provided customer number and then enrich the original payload with that information.

Since Spring Integration 2.1, the Payload Enricher is provided.
A Payload Enricher defines an endpoint that passes a `Message` to the exposed request channel and then expects a reply message.
The reply message then becomes the root object for evaluation of expressions to enrich the target payload.

The Payload Enricher provides full XML namespace support via the `enricher` element.
In order to send request messages, the payload enricher has a `request-channel` attribute that allows you to dispatch messages to a request channel.

Basically by defining the request channel, the Payload Enricher acts as a Gateway, waiting for the message that were sent to the request channel to return, and the Enricher then augments the message's payload with the data provided by the reply message.

When sending messages to the request channel you also have the option to only send a subset of the original payload using the `request-payload-expression` attribute.

The enriching of payloads is configured through SpEL expressions, providing users with a maximum degree of flexibility.
Therefore, users are not only able to enrich payloads with direct values from the reply channel's `Message`, but they can use SpEL expressions to extract a subset from that Message, only, or to apply addtional inline transformations, allowing them to further manipulate the data.

If you only need to enrich payloads with static values, you don't have to provide the `request-channel` attribute.

NOTE: Enrichers are a variant of Transformers and in many cases you could use a Payload Enricher or a generic Transformer implementation to add additional data to your messages payloads.
Thus, familiarize yourself with all transformation-capable components that are provided by Spring Integration and carefully select the implementation that semantically fits your business case best.

[[payload-enricher-configuration]]
===== Configuration

Below, please find an overview of all available configuration options that are available for the payload enricher:

[source,xml]
----
<int:enricher request-channel=""                           <1>
              auto-startup="true"                          <2>
              id=""                                        <3>
              order=""                                     <4>
              output-channel=""                            <5>
              request-payload-expression=""                <6>
              reply-channel=""                             <7>
              error-channel=""                             <8>
              send-timeout=""                              <9>
              should-clone-payload="false">                <10>
    <int:poller></int:poller>                              <11>
    <int:property name="" expression="" null-result-expression="'Could not determine the name'"/>   <12>
    <int:property name="" value="23" type="java.lang.Integer" null-result-expression="'0'"/>
    <int:header name="" expression="" null-result-expression=""/>   <13>
    <int:header name="" value="" overwrite="" type="" null-result-expression=""/>
</int:enricher>
----

<1> Channel to which a Message will be sent to get the data to use for enrichment.
_Optional_.


<2> Lifecycle attribute signaling if this component should be started during Application Context startup.
Defaults to true._Optional_.


<3> Id of the underlying bean definition, which is either an `EventDrivenConsumer` or a `PollingConsumer`.
_Optional_.


<4> Specifies the order for invocation when this endpoint is connected as a subscriber to a channel.
This is particularly relevant when that channel is using a "failover" dispatching strategy.
It has no effect when this endpoint itself is a Polling Consumer for a channel with a queue.
_Optional_.


<5> Identifies the Message channel where a Message will be sent after it is being processed by this endpoint._Optional_.


<6> By default the original message's payload will be used as payload that will be send to the `request-channel`.
By specifying a SpEL expression as value for the `request-payload-expression` attribute, a subset of the original payload, a header value or any other resolvable SpEL expression can be used as the basis for the payload, that will be sent to the request-channel.
For the Expression evaluation the full message is available as the 'root object'.
For instance the following SpEL expressions (among others) are possible:
`payload.foo`,
`headers.foobar`,
`new java.util.Date()`,
`'foo' + 'bar'`.


<7> Channel where a reply Message is expected.
This is optional; typically the auto-generated temporary reply channel is sufficient.
_Optional_.


<8> Channel to which an `ErrorMessage` will be sent if an `Exception` occurs downstream of the `request-channel`.
This enables you to return an alternative object to use for enrichment.
This is optional; if it is not set then `Exception` is thrown to the caller.
_Optional_.


<9> Maximum amount of time in milliseconds to wait when sending a message to the channel, if such channel may block.
For example, a Queue Channel can block until space is available, if its maximum capacity has been reached.
Internally the send timeout is set on the `MessagingTemplate` and ultimately applied when invoking the send operation on the `MessageChannel`.
By default the send timeout is set to '-1', which may cause the send operation on the `MessageChannel`, depending on the implementation, to block indefinitely.
_Optional_.


<10> Boolean value indicating whether any payload that implements `Cloneable` should be cloned prior to sending the Message to the request chanenl for acquiring the enriching data.
The cloned version would be used as the target payload for the ultimate reply.
Default is `false`.
_Optional_.


<11> Allows you to configure a Message Poller if this endpoint is a Polling Consumer.
_Optional_.


<12> Each `property` sub-element provides the name of a property (via the mandatory `name` attribute).
That property should be settable on the target payload instance.
Exactly one of the `value` or `expression` attributes must be provided as well.
The former for a literal value to set, and the latter for a SpEL expression to be evaluated.
The root object of the evaluation context is the Message that was returned from the flow initiated by this enricher, the input Message if there is no request channel, or the application context (using the '@<beanName>.<beanProperty>' SpEL syntax).
Starting with _4.0_, when specifying a `value` attribute, you can also specify an optional `type` attribute.
When the destination is a typed setter method, the framework will coerce the value appropriately (as long as a `PropertyEditor`) exists to handle the conversion.
If however, the target payload is a `Map` the entry will be populated with the value without conversion.
The `type` attribute allows you to, say, convert a String containing a number to an `Integer` value in the target payload.
Starting with _4.1_, you can also specify an optional `null-result-expression` attribute.
When the `enricher` returns null, it will be evaluated and the output of the evaluation will be returned instead.


<13> Each `header` sub-element provides the name of a Message header (via the mandatory `name` attribute).
Exactly one of the `value` or `expression` attributes must be provided as well.
The former for a literal value to set, and the latter for a SpEL expression to be evaluated.
The root object of the evaluation context is the Message that was returned from the flow initiated by this enricher, the input Message if there is no request channel, or the application context (using the '@<beanName>.<beanProperty>' SpEL syntax).
Note, similar to the `<header-enricher>`, the `<enricher>`'s `header` element has `type` and `overwrite` attributes.
However, a difference is that, with the `<enricher>`, the `overwrite` attribute is `true` by default, to be consistent with `<enricher>`'s `<property>` sub-element.
Starting with _4.1_, you can also specify an optional `null-result-expression` attribute.
When the `enricher` returns null, it will be evaluated and the output of the evaluation will be returned instead.

[[payload-enricher-examples]]
===== Examples

Below, please find several examples of using a Payload Enricher in various situations.

In the following example, a `User` object is passed as the payload of the `Message`.
The `User` has several properties but only the `username` is set initially.
The Enricher's `request-channel` attribute below is configured to pass the `User` on to the `findUserServiceChannel`.

Through the implicitly set `reply-channel` a `User` object is returned and using the `property` sub-element, properties from the reply are extracted and used to enrich the original payload.

[source,xml]
----
<int:enricher id="findUserEnricher"
              input-channel="findUserEnricherChannel"
              request-channel="findUserServiceChannel">
    <int:property name="email"    expression="payload.email"/>
    <int:property name="password" expression="payload.password"/>
</int:enricher>
----

NOTE: The code samples shown here, are part of the _Spring
              Integration Samples_ project.
Please feel free to check it out at:null

_How do I pass only a subset of data to the request channel?_

Using a `request-payload-expression` attribute a single property of the payload can be passed on to the request channel instead of the full message.
In the example below on the username property is passed on to the request channel.
Keep in mind, that although only the username is passed on, the resulting message send to the request channel will contain the full set of `MessageHeaders`.

[source,xml]
----
<int:enricher id="findUserByUsernameEnricher"
              input-channel="findUserByUsernameEnricherChannel"
              request-channel="findUserByUsernameServiceChannel"
              request-payload-expression="payload.username">
    <int:property name="email"    expression="payload.email"/>
    <int:property name="password" expression="payload.password"/>
</int:enricher>
----

_How can I enrich payloads that consist of Collection data?_

In the following example, instead of a `User` object, a `Map` is passed in.
The `Map` contains the username under the map key `username`.
Only the `username` is passed on to the request channel.
The reply contains a full `User` object, which is ultimately added to the `Map` under the `user` key.

[source,xml]
----
<int:enricher id="findUserWithMapEnricher"
              input-channel="findUserWithMapEnricherChannel"
              request-channel="findUserByUsernameServiceChannel"
              request-payload-expression="payload.username">
    <int:property name="user" expression="payload"/>
</int:enricher>
----

_How can I enrich payloads with static information without using a request channel?_

Here is an example that does not use a request channel at all, but solely enriches the message's payload with static values.
But please be aware that the word 'static' is used loosely here.
You can still use SpEL expressions for setting those values.

[source,xml]
----
<int:enricher id="userEnricher"
              input-channel="input">
    <int:property name="user.updateDate" expression="new java.util.Date()"/>
    <int:property name="user.firstName" value="foo"/>
    <int:property name="user.lastName"  value="bar"/>
    <int:property name="user.age"       value="42"/>
</int:enricher>
----
