[[filter]]
=== Filter

[[filter-introduction]]
==== Introduction

Message Filters are used to decide whether a Message should be passed along or dropped based on some criteria such as a Message Header value or Message content itself.
Therefore, a Message Filter is similar to a router, except that for each Message received from the filter's input channel, that same Message may or may not be sent to the filter's output channel.
Unlike the router, it makes no decision regarding _which_ Message Channel to send the Message to but only decides _whether_ to send.

NOTE: As you will see momentarily, the Filter also supports a discard channel, so in certain cases it _can_ play the role of a very simple router (or "switch") based on a boolean condition.

In Spring Integration, a Message Filter may be configured as a Message Endpoint that delegates to an implementation of the `MessageSelector` interface.
That interface is itself quite simple:
[source,java]
----
public interface MessageSelector {

    boolean accept(Message<?> message);

}
----

The `MessageFilter` constructor accepts a selector instance:

[source,java]
----
MessageFilter filter = new MessageFilter(someSelector);
----

In combination with the namespace and SpEL, very powerful filters can be configured with very little java code.
[[filter-config]]
==== Configuring Filter

[[filter-xml]]
===== Configuring a Filter with XML

The <filter> element is used to create a Message-selecting endpoint.
In addition to "`input-channel` and `output-channel` attributes, it requires a `ref`.
The `ref` may point to a `MessageSelector` implementation:
[source,xml]
----
<int:filter input-channel="input" ref="selector" output-channel="output"/>

<bean id="selector" class="example.MessageSelectorImpl"/>
----

Alternatively, the `method` attribute can be added at which point the `ref` may refer to any object.
The referenced method may expect either the `Message` type or the payload type of inbound Messages.
The method must return a boolean value.
If the method returns 'true', the Message _will_ be sent to the output-channel.

[source,xml]
----
<int:filter input-channel="input" output-channel="output"
    ref="exampleObject" method="someBooleanReturningMethod"/>

<bean id="exampleObject" class="example.SomeObject"/>
----

If the selector or adapted POJO method returns `false`, there are a few settings that control the handling of the rejected Message.
By default (if configured like the example above), rejected Messages will be silently dropped.
If rejection should instead result in an error condition, then set the `throw-exception-on-rejection` attribute to `true`:
[source,xml]
----
<int:filter input-channel="input" ref="selector"
    output-channel="output" throw-exception-on-rejection="true"/>
----

If you want rejected messages to be routed to a specific channel, provide that reference as the `discard-channel`:
[source,xml]
----
<int:filter input-channel="input" ref="selector"
    output-channel="output" discard-channel="rejectedMessages"/>
----

NOTE: Message Filters are commonly used in conjunction with a Publish Subscribe Channel.
Many filter endpoints may be subscribed to the same channel, and they decide whether or not to pass the Message to the next endpoint which could be any of the supported types (e.g.
Service Activator).
This provides a _reactive_ alternative to the more _proactive_ approach of using a Message Router with a single Point-to-Point input channel and multiple output channels.

Using a `ref` attribute is generally recommended if the custom filter implementation is referenced in other `<filter>` definitions.
However if the custom filter implementation is scoped to a single `<filter>` element, provide an inner bean definition:
[source,xml]
----
<int:filter method="someMethod" input-channel="inChannel" output-channel="outChannel">
  <beans:bean class="org.foo.MyCustomFilter"/>
</filter>
----

NOTE: Using both the `ref` attribute and an inner handler definition in the same `<filter>` configuration is not allowed, as it creates an ambiguous condition, and an Exception will be thrown.

With the introduction of SpEL support, Spring Integration added the `expression` attribute to the filter element.
It can be used to avoid Java entirely for simple filters.
[source,xml]
----
<int:filter input-channel="input" expression="payload.equals('nonsense')"/>
----

The string passed as the expression attribute will be evaluated as a SpEL expression with the Message available in the evaluation context.
If it is necessary to include the result of an expression in the scope of the application context you can use the #{} notation as defined in the http://docs.spring.io/spring/docs/current/spring-framework-reference/html/expressions.html#expressions-beandef[SpEL reference documentation].

[source,xml]
----
<int:filter input-channel="input"
            expression="payload.matches(#{filterPatterns.nonsensePattern})"/>
----

If the Expression itself needs to be dynamic, then an 'expression' sub-element may be used.
That provides a level of indirection for resolving the Expression by its key from an ExpressionSource.
That is a strategy interface that you can implement directly, or you can rely upon a version available in Spring Integration that loads Expressions from a "resource bundle" and can check for modifications after a given number of seconds.
All of this is demonstrated in the following configuration sample where the Expression could be reloaded within one minute if the underlying file had been modified.
If the ExpressionSource bean is named "expressionSource", then it is not necessary to provide the` source` attribute on the <expression> element, but in this case it's shown for completeness.

[source,xml]
----
<int:filter input-channel="input" output-channel="output">
    <int:expression key="filterPatterns.example" source="myExpressions"/>
</int:filter>

<beans:bean id="myExpressions" id="myExpressions"
    class="o.s.i.expression.ReloadableResourceBundleExpressionSource">
    <beans:property name="basename" value="config/integration/expressions"/>
    <beans:property name="cacheSeconds" value="60"/>
</beans:bean>

----

Then, the 'config/integration/expressions.properties' file (or any more specific version with a locale extension to be resolved in the typical way that resource-bundles are loaded) would contain a key/value pair:
[source,xml]
----
filterPatterns.example=payload > 100
----

NOTE: All of these examples that use `expression` as an attribute or sub-element can also be applied within transformer, router, splitter, service-activator, and header-enricher elements.
Of course, the semantics/role of the given component type would affect the interpretation of the evaluation result in the same way that the return value of a method-invocation would be interpreted.
For example, an expression can return Strings that are to be treated as Message Channel names by a router component.
However, the underlying functionality of evaluating the expression against the Message as the root object, and resolving bean names if prefixed with '@' is consistent across all of the core EIP components within Spring Integration.

[[filter-annotations]]
===== Configuring a Filter with Annotations

A filter configured using annotations would look like this.

[source,java]
----
public class PetFilter {
    ...
    @Filter  <1>
    public boolean dogsOnly(String input) {
        ...
    }
}
----

<1> An annotation indicating that this method shall be used as a filter.
Must be specified if this class will be used as a filter.


All of the configuration options provided by the xml element are also available for the `@Filter` annotation.

The filter can be either referenced explicitly from XML or, if the `@MessageEndpoint` annotation is defined on the class, detected automatically through classpath scanning.

Also see <<advising-with-annotations>>.
