[[gateway]]
=== Messaging Gateways

The primary purpose of a Gateway is to hide the messaging API provided by Spring Integration.
It allows your application's business logic to be completely unaware of the Spring Integration API and using a generic Gateway, your code interacts instead with a simple interface, only.

[[gateway-proxy]]
==== Enter the GatewayProxyFactoryBean

As mentioned above, it would be great to have no dependency on the Spring Integration API at all - including the gateway class.
For that reason, Spring Integration provides the `GatewayProxyFactoryBean` that generates a proxy for any interface and internally invokes the gateway methods shown below.
Using dependency injection you can then expose the interface to your business methods.

Here is an example of an interface that can be used to interact with Spring Integration:

[source,java]
----
package org.cafeteria;

public interface Cafe {

    void placeOrder(Order order);

}
----

[[gateway-namespace]]
==== Gateway XML Namespace Support

Namespace support is also provided which allows you to configure such an interface as a service as demonstrated by the following example.

[source,xml]
----
<int:gateway id="cafeService"
         service-interface="org.cafeteria.Cafe"
         default-request-channel="requestChannel"
         default-reply-timeout="10000"
         default-reply-channel="replyChannel"/>
----

With this configuration defined, the "cafeService" can now be injected into other beans, and the code that invokes the methods on that proxied instance of the Cafe interface has no awareness of the Spring Integration API.
The general approach is similar to that of Spring Remoting (RMI, HttpInvoker, etc.).
See the "Samples" Appendix for an example that uses this "gateway" element (in the Cafe demo).

The defaults in the configuration above are applied to all methods on the gateway interface; if a reply timeout is not
specified, the calling thread will wait indefinitely for a reply.
See <<gateway-no-response>>.

The defaults can be overridden for individual methods; see <<gateway-configuration-annotations>>.

[[gateway-default-reply-channel]]
==== Setting the Default Reply Channel

Typically you don't have to specify the `default-reply-channel`, since a Gateway will auto-create a temporary, anonymous reply channel, where it will listen for the reply.
However, there are some cases which may prompt you to define a `default-reply-channel` (or `reply-channel` with adapter gateways such as HTTP, JMS, etc.).

For some background, we'll quickly discuss some of the inner-workings of the Gateway.
A Gateway will create a temporary point-to-point reply channel which is anonymous and is added to the Message Headers with the name `replyChannel`.
When providing an explicit `default-reply-channel` (`reply-channel` with remote adapter gateways), you have the option to point to a publish-subscribe channel, which is so named because you can add more than one subscriber to it.
Internally Spring Integration will create a Bridge between the temporary `replyChannel` and the explicitly defined `default-reply-channel`.

So let's say you want your reply to go not only to the gateway, but also to some other consumer.
In this case you would want two things: _a) a named channel you can subscribe to and b) that channel is a publish-subscribe-channel._ The default strategy used by the gateway will not satisfy those needs, because the reply channel added to the header is anonymous and point-to-point.
This means that no other subscriber can get a handle to it and even if it could, the channel has point-to-point behavior such that only one subscriber would get the Message.
So by defining a `default-reply-channel` you can point to a channel of your choosing, which in this case would be a `publish-subscribe-channel`.
The Gateway would create a bridge from it to the temporary, anonymous reply channel that is stored in the header.

Another case where you might want to provide a reply channel explicitly is for monitoring or auditing via an interceptor (e.g., wiretap).
You need a named channel in order to configure a Channel Interceptor.

[[gateway-configuration-annotations]]
==== Gateway Configuration with Annotations and/or XML

[source,java]
----
public interface Cafe {

    @Gateway(requestChannel="orders")
    void placeOrder(Order order);

}
----

You may alternatively provide such content in `method` sub-elements if you prefer XML configuration (see the next paragraph).

It is also possible to pass values to be interpreted as Message headers on the Message that is created and sent to the
request channel by using the `@Header` annotation:

[source,java]
----
public interface FileWriter {

    @Gateway(requestChannel="filesOut")
    void write(byte[] content, @Header(FileHeaders.FILENAME) String filename);

}
----

If you prefer the XML approach of configuring Gateway methods, you can provide _method_ sub-elements to the gateway configuration.

[source,xml]
----
<int:gateway id="myGateway" service-interface="org.foo.bar.TestGateway"
      default-request-channel="inputC">
  <int:default-header name="calledMethod" expression="#gatewayMethod.name"/>
  <int:method name="echo" request-channel="inputA" reply-timeout="2" request-timeout="200"/>
  <int:method name="echoUpperCase" request-channel="inputB"/>
  <int:method name="echoViaDefault"/>
</int:gateway>
----

You can also provide individual headers per method invocation via XML.
This could be very useful if the headers you want to set are static in nature and you don't want to embed them in the gateway's method signature via `@Header` annotations.
For example, in the Loan Broker example we want to influence how aggregation of the Loan quotes will be done based on what type of request was initiated (single quote or all quotes).
Determining the type of the request by evaluating what gateway method was invoked, although possible, would violate the separation of concerns paradigm (the method is a java artifact),  but expressing your intention (meta information) via Message headers is natural in a Messaging architecture.

[source,xml]
----
<int:gateway id="loanBrokerGateway"
         service-interface="org.springframework.integration.loanbroker.LoanBrokerGateway">
  <int:method name="getLoanQuote" request-channel="loanBrokerPreProcessingChannel">
    <int:header name="RESPONSE_TYPE" value="BEST"/>
  </int:method>
  <int:method name="getAllLoanQuotes" request-channel="loanBrokerPreProcessingChannel">
    <int:header name="RESPONSE_TYPE" value="ALL"/>
  </int:method>
</int:gateway>
----

In the above case you can clearly see how a different value will be set for the 'RESPONSE_TYPE' header based on the gateway's method.

*Expressions and "Global" Headers*

The `<header/>` element supports `expression` as an alternative to `value`.
The SpEL expression is evaluated to determine the value of the header.
There is no `#root` object but the following variables are available:

#args - an `Object[]` containing the method arguments


#gatewayMethod - the `java.reflect.Method` object representing the method in the `service-interface` that was invoked.
A header containing this variable can be used later in the flow, for example, for routing.
For example, if you wish to route on the simple method name, you might add a header, with expression `#gatewayMethod.name`.

NOTE: The `java.reflect.Method` is not serializable; a header with expression `#gatewayMethod` will be lost if you later serialize the message.
So, you may wish to use `#gatewayMethod.name` or `#gatewayMethod.toString()` in those cases; the `toString()` method provides a String representation of the method, including parameter and return types.

Since 3.0, `<default-header/>` s can be defined to add headers to all messages produced by the gateway, regardless of the method invoked.
Specific headers defined for a method take precedence over default headers.
Specific headers defined for a method here will override any `@Header` annotations in the service interface.
However, default headers will NOT override any `@Header` annotations in the service interface.

The gateway now also supports a `default-payload-expression` which will be applied for all methods (unless overridden).

[[gateway-mapping]]
==== Mapping Method Arguments to a Message

Using the configuration techniques in the previous section allows control of how method arguments are mapped to message elements (payload and header(s)).
When no explicit configuration is used, certain conventions are used to perform the mapping.
In some cases, these conventions cannot determine which argument is the payload and which should be mapped to headers.

[source,java]
----

public String send1(Object foo, Map bar);

public String send2(Map foo, Map bar);

----

In the first case, the convention will map the first argument to the payload (as long as it is not a `Map`) and the contents of the second become headers.

In the second case (or the first when the argument for parameter `foo` is a `Map`), the framework cannot determine which argument should be the payload; mapping will fail.
This can generally be resolved using a `payload-expression`, a `@Payload` annotation and/or a `@Headers` annotation.

Alternatively, and whenever the conventions break down, you can take the entire responsibility for mapping the method calls to messages.
To do this, implement an `MethodArgsMessageMapper` and provide it to the `<gateway/>` using the `mapper` attribute.
The mapper maps a `MethodArgsHolder`, which is a simple class wrapping the `java.reflect.Method` instance and an `Object[]` containing the arguments.
When providing a custom mapper, the `default-payload-expression` attribute and `<default-header/>` elements are not allowed on the gateway; similarly, the `payload-expression` attribute and `<header/>` elements are not allowed on any `<method/>` elements.

*Mapping Method Arguments*

Here are examples showing how method arguments can be mapped to the message (and some examples of invalid configuration):

[source,java]
----
public interface MyGateway {

    void payloadAndHeaderMapWithoutAnnotations(String s, Map<String, Object> map);

    void payloadAndHeaderMapWithAnnotations(@Payload String s, @Headers Map<String, Object> map);

    void headerValuesAndPayloadWithAnnotations(@Header("k1") String x, @Payload String s, @Header("k2") String y);

    void mapOnly(Map<String, Object> map); // the payload is the map and no custom headers are added

    void twoMapsAndOneAnnotatedWithPayload(@Payload Map<String, Object> payload, Map<String, Object> headers);

    @Payload("#args[0] + #args[1] + '!'")
    void payloadAnnotationAtMethodLevel(String a, String b);

    @Payload("@someBean.exclaim(#args[0])")
    void payloadAnnotationAtMethodLevelUsingBeanResolver(String s);

    void payloadAnnotationWithExpression(@Payload("toUpperCase()") String s);

    void payloadAnnotationWithExpressionUsingBeanResolver(@Payload("@someBean.sum(#this)") String s); //  <1>

    // invalid
    void twoMapsWithoutAnnotations(Map<String, Object> m1, Map<String, Object> m2);

    // invalid
    void twoPayloads(@Payload String s1, @Payload String s2);

    // invalid
    void payloadAndHeaderAnnotationsOnSameParameter(@Payload @Header("x") String s);

    // invalid
    void payloadAndHeadersAnnotationsOnSameParameter(@Payload @Headers Map<String, Object> map);

}

----

<1> Note that in this example, the SpEL variable `#this` refers to the argument - in this case, the value of `'s'`.

The XML equivalent looks a little different, since there is no `#this` context for the method argument, but expressions can refer to method arguments using the `#args` variable:
[source,xml]
----
<int:gateway id="myGateway" service-interface="org.foo.bar.MyGateway">
  <int:method name="send1" payload-expression="#args[0] + 'bar'"/>
  <int:method name="send2" payload-expression="@someBean.sum(#args[0])"/>
  <int:method name="send3" payload-expression="#method"/>
  <int:method name="send4">
    <int:header name="foo" expression="#args[2].toUpperCase()"/>
  </int:method>
</int:gateway>
----

[[messaging-gateway-annotation]]
==== @MessagingGateway Annotation

Starting with _version 4.0_, gateway service interfaces can be marked with a `@MessagingGateway` annotation instead of requiring the definition of a `<gateway />` xml element for configuration.
The following compares the two approaches for configuring the same gateway:

[source,xml]
----
<int:gateway id="myGateway" service-interface="org.foo.bar.TestGateway"
      default-request-channel="inputC">
  <int:default-header name="calledMethod" expression="#gatewayMethod.name"/>
  <int:method name="echo" request-channel="inputA" reply-timeout="2" request-timeout="200"/>
  <int:method name="echoUpperCase" request-channel="inputB">
  		<int:header name="foo" value="bar"/>
  </int:method>
  <int:method name="echoViaDefault"/>
</int:gateway>
----

[source,java]
----
@MessagingGateway(name = "myGateway", defaultRequestChannel = "inputC",
		  defaultHeaders = @GatewayHeader(name = "calledMethod",
		                           expression="#gatewayMethod.name"))
public interface TestGateway {

   @Gateway(requestChannel = "inputA", replyTimeout = 2, requestTimeout = 200)
   String echo(String payload);

   @Gateway(requestChannel = "inputB", headers = @GatewayHeader(name = "foo", value="bar"))
   String echoUpperCase(String payload);

   String echoViaDefault(String payload);

}
----

IMPORTANT: As with the XML version, Spring Integration creates the `proxy` implementation with its messaging infrastructure, when discovering these annotations during a component scan.
To perform this scan and register the `BeanDefinition` in the application context, add the `@IntegrationComponentScan` annotation to a `@Configuration` class.
The standard `@ComponentScan` infrastructure doesn't deal with interfaces, therefore the custom `@IntegrationComponentScan` logic has been introduced
to determine `@MessagingGateway` annotation on the interfaces and register `GatewayProxyFactoryBean` s for them.
See also <<annotations>>

NOTE: If you have no XML configuration, the `@EnableIntegration` annotation is required on at least one `@Configuration`
class.
See <<configuration-enable-integration>> for more information.

[[gateway-calling-no-argument-methods]]
==== Invoking No-Argument Methods

When invoking methods on a Gateway interface that do not have any arguments, the default behavior is to _receive_ a `Message` from a `PollableChannel`.

At times however, you may want to trigger no-argument methods so that you can in fact interact with other components downstream that do not require user-provided parameters, e.g.
triggering no-argument SQL calls or Stored Procedures.

In order to achieve _send-and-receive_ semantics, you must provide a payload.
In order to generate a payload, method parameters on the interface are not necessary.
You can either use the `@Payload` annotation or the `payload-expression` attribute in XML on the `method` sub-element.
Below please find a few examples of what the payloads could be:

* a literal string
* #gatewayMethod.name
* new java.util.Date()
* @someBean.someMethod()'s return value



Here is an example using the `@Payload` annotation:

[source,xml]
----
public interface Cafe {

    @Payload("new java.util.Date()")
    List<Order> retrieveOpenOrders();

}
----

If a method has no argument and no return value, but does contain a payload expression, it will be treated as a _send-only_ operation.

[[gateway-error-handling]]
==== Error Handling

Of course, the Gateway invocation might result in errors.
By default, any error that occurs downstream will be re-thrown as is upon the Gateway's method invocation.
For example, consider the following simple flow:

[source]
----
gateway -> service-activator
----

If the service invoked by the service activator throws a `FooException`, the framework wraps it in a `MessagingException`, attaching the message passed to the service activator in the `failedMessage` property.
Any logging performed by the framework will therefore have full context of the failure.
When the exception is caught by the gateway, by default, the `FooException` will be unwrapped and thrown to the caller.
You can configure a `throws` clause on the gateway method declaration for matching the particular exception type in the cause chain.
For example if you would like to catch a whole `MessagingException` with all the messaging information of the reason of downstream error, you should have a gateway method like this:

[source, java]
----
public interface MyGateway {

    void performProcess() throws MessagingException;

}
----

Since we encourage POJO programming, you may not want to expose the caller to messaging infrastructure.

If your gateway method does not have a `throws` clause, the gateway will traverse the cause tree looking for a `RuntimeException` (that is not a `MessagingException`).
If none is found, the framework will simply throw the `MessagingException`.
If the `FooException` in the discussion above has a cause `BarException` and your method `throws BarException` then the gateway will further unwrap that and throw it to the caller.

When a gateway is declared with no `service-interface`, an internal framework interface `RequestReplyExchanger` is used.

[source, java]
----
public interface RequestReplyExchanger {

	Message<?> exchange(Message<?> request) throws MessagingException;

}
----

Before _version 5.0_ this `exchange` method did not have a `throws` clause and therefore the exception was unwrapped.
If you are using this interface, and wish to restore the previous unwrap behavior, use a custom `service-interface` instead, or simply access the `cause` of the  `MessagingException` yourself.

However there are times when you may want to simply log the error rather than propagating it, or you may want to treat an Exception as a valid reply, by mapping it to a Message that will conform to some "error message" contract that the caller understands.
To accomplish this, the Gateway provides support for a Message Channel dedicated to the errors via the _error-channel_ attribute.
In the example below, you can see that a 'transformer' is used to create a reply `Message` from the `Exception`.

[source,xml]
----
<int:gateway id="sampleGateway"
    default-request-channel="gatewayChannel"
    service-interface="foo.bar.SimpleGateway"
    error-channel="exceptionTransformationChannel"/>

<int:transformer input-channel="exceptionTransformationChannel"
        ref="exceptionTransformer" method="createErrorResponse"/>

----

The _exceptionTransformer_ could be a simple POJO that knows how to create the expected error response objects.
That would then be the payload that is sent back to the caller.
Obviously, you could do many more elaborate things in such an "error flow" if necessary.
It might involve routers (including Spring Integration's `ErrorMessageExceptionTypeRouter`), filters, and so on.
Most of the time, a simple 'transformer' should be sufficient, however.

Alternatively, you might want to only log the Exception (or send it somewhere asynchronously).
If you provide a one-way flow, then nothing would be sent back to the caller.
In the case that you want to completely suppress Exceptions, you can provide a reference to the global "nullChannel" (essentially a /dev/null approach).
Finally, as mentioned above, if no "error-channel" is defined at all, then the Exceptions will propagate as usual.

When using the `@MessagingGateway` annotation (see <<messaging-gateway-annotation>>), use the `errroChannel` attribute.

Starting with _version 5.0_, when using a gateway method with a `void` return type (one-way flow), the `error-channel` reference (if provided) is populated in the standard `errorChannel` header of each message sent.
This allows a downstream async flow, based on the standard `ExecutorChannel` configuration (or a `QueueChannel`), to override a default global `errorChannel` exceptions sending behavior.
Previously you had to specify an `errorChannel` header manually via `@GatewayHeader` annotation or `<header>` sub-element.
The `error-channel` property was ignored for `void` methods with an asynchronous flow; error messages were sent to the default `errorChannel` instead.


IMPORTANT: Exposing the messaging system via simple POJI Gateways obviously provides benefits, but "hiding" the reality of the underlying messaging system does come at a price so there are certain things you should consider.
We want our Java method to return as quickly as possible and not hang for an indefinite amount of time while the caller is waiting on it to return (void, return value, or a thrown Exception).
When regular methods are used as a proxies in front of the Messaging system, we have to take into account the potentially asynchronous nature of the underlying messaging.
This means that there might be a chance that a Message that was initiated by a Gateway could be dropped by a Filter, thus never reaching a component that is responsible for producing a reply.
Some Service Activator method might result in an Exception, thus providing no reply (as we don't generate Null messages).
So as you can see there are multiple scenarios where a reply message might not be coming.
That is perfectly natural in messaging systems.
However think about the implication on the gateway method. The Gateway's method input arguments  were incorporated into a Message and sent downstream.
The reply Message would be converted to a return value of the Gateway's method.
So you might want to ensure that for each Gateway call there will always be a reply Message.
Otherwise, your Gateway method might never return and will hang indefinitely.
One of the ways of handling this situation is via an Asynchronous Gateway (explained later in this section).
Another way of handling it is to explicitly set the reply-timeout attribute.
That way, the gateway will not hang any longer than the time specified by the reply-timeout and will return 'null' if that timeout does elapse.
Finally, you might want to consider setting downstream flags such as 'requires-reply' on a service-activator or 'throw-exceptions-on-rejection' on a filter. These options will be discussed in more detail in the final section of this chapter.

NOTE: If the downstream flow returns an `ErrorMessage`, its `payload` (a `Throwable`) is treated as a regular downstream
error: if there is an `error-channel` configured, it will be sent there, to the error flow; otherwise the payload is
thrown to the caller of gateway.
Similarly, if the error flow on the `error-channel` returns an `ErrorMessage` its payload is thrown to the caller.
The same applies to any message with a `Throwable` payload.
This can be useful in async situations when when there is a need propagate an `Exception` directly to the caller.
To achieve this you can either return an `Exception` as the `reply` from some service, or simply throw it.
Generally, even with an async flow, the framework will take care of propagating an exception thrown by the
downstream flow back to the gateway.
The https://github.com/spring-projects/spring-integration-samples/tree/master/intermediate/tcp-client-server-multiplex[TCP Client-Server Multiplex]
sample demonstrates both techniques to return the exception to the caller.
It emulates a Socket IO error to the waiting thread using an `aggregator` with `group-timeout` (see <<agg-and-group-to>>)
and `MessagingTimeoutException` reply on the discard flow.

[[gateway-timeouts]]
==== Gateway Timeouts

There are two properties `requestTimeout` and `replyTimeout`.
The request timeout only applies if the channel can block (e.g. a bounded `QueueChannel` that is full).
The reply timeout is how long the gateway will wait for a reply, or return `null`; it defaults to infinity.

The timeouts can be set as defaults for all methods on the gateway (`defaultRequestTimeout`, `defaultReplyTimeout`) (or on the `MessagingGateway` interface annotation).
Individual methods can override these defaults (in `<method/>` child elements) or on the `@Gateway` annotation.

Starting with _version 5.0_, the timeouts can be defined as expressions:

[source, java]
----
@Gateway(payloadExpression = "#args[0]", requestChannel = "someChannel",
        requestTimeoutExpression = "#args[1]", replyTimeoutExpression = "#args[2]")
String lateReply(String payload, long requestTimeout, long replyTimeout);
----

The evaluation context has a `BeanResolver` (use `@someBean` to reference other beans) and the `#args` array variable is available.

When configuring with XML, the timeout attributes can be a simple long value or a SpEL expression.

[source, xml]
----
<method name="someMethod" request-channel="someRequestChannel"
                      payload-expression="#args[0]"
                      request-timeout="1000"
                      reply-timeout="#args[1]">
</method>
----

[[async-gateway]]
==== Asynchronous Gateway

===== Introduction

As a pattern, the Messaging Gateway is a very nice way to hide messaging-specific code while still exposing the full capabilities of the messaging system.
As you've seen, the `GatewayProxyFactoryBean` provides a convenient way to expose a Proxy over a service-interface thus giving you POJO-based access to a messaging system (based on objects in your own domain, or primitives/Strings, etc).
 But when a gateway is exposed via simple POJO methods which return values it does imply that for each Request message (generated when the method is invoked) there must be a Reply message (generated when the method has returned).
Since Messaging systems naturally are asynchronous you may not always be able to guarantee the contract where _"for each request there will always be be a reply"_.  With Spring Integration 2.0 we introduced support for an _Asynchronous Gateway_ which is a convenient way to initiate flows where you may not know if a reply is expected or how long will it take for replies to arrive.

A natural way to handle these types of scenarios in Java would be relying upon _java.util.concurrent.Future_ instances, and that is exactly what Spring Integration uses to support an _Asynchronous Gateway_.

From the XML configuration, there is nothing different and you still define _Asynchronous Gateway_ the same way as a regular Gateway.

[source,xml]
----
<int:gateway id="mathService" 
     service-interface="org.springframework.integration.sample.gateway.futures.MathServiceGateway"
     default-request-channel="requestChannel"/>
----

However the Gateway Interface (service-interface) is a little different:

[source,java]
----
public interface MathServiceGateway {

  Future<Integer> multiplyByTwo(int i);

}
----

As you can see from the example above, the return type for the gateway method is a `Future`.
When `GatewayProxyFactoryBean` sees that the return type of the gateway method is a `Future`, it immediately switches to the async mode by utilizing an `AsyncTaskExecutor`.
That is all.
The call to such a method always returns immediately with a `Future` instance.
Then, you can interact with the `Future` at your own pace to get the result, cancel, etc.
And, as with any other use of Future instances, calling get() may reveal a timeout, an execution exception, and so on.
[source,java]
----
MathServiceGateway mathService = ac.getBean("mathService", MathServiceGateway.class);
Future<Integer> result = mathService.multiplyByTwo(number);
// do something else here since the reply might take a moment
int finalResult =  result.get(1000, TimeUnit.SECONDS);
----

For a more detailed example, please refer to the https://github.com/spring-projects/spring-integration-samples/tree/master/intermediate/async-gateway[_async-gateway_] sample distributed within the Spring Integration samples.

===== ListenableFuture

Starting with _version 4.1_, async gateway methods can also return `ListenableFuture` (introduced in Spring Framework 4.0).
These return types allow you to provide a callback which is invoked when the result is available (or an exception occurs).
When the gateway detects this return type, and the task executor (see below) is an `AsyncListenableTaskExecutor`, the executor's `submitListenable()` method is invoked.

[source,java]
----
ListenableFuture<String> result = this.asyncGateway.async("foo");
result.addCallback(new ListenableFutureCallback<String>() {

    @Override
    public void onSuccess(String result) {
        ...
    }

    @Override
    public void onFailure(Throwable t) {
        ...
    }
});
----

===== AsyncTaskExecutor

By default, the `GatewayProxyFactoryBean` uses `org.springframework.core.task.SimpleAsyncTaskExecutor` when submitting internal `AsyncInvocationTask` instances for any gateway method whose return type is `Future`.
However the `async-executor` attribute in the `<gateway/>` element's configuration allows you to provide a reference to any implementation of `java.util.concurrent.Executor` available within the Spring application context.

The (default) `SimpleAsyncTaskExecutor` supports both `Future` and `ListenableFuture` return types, returning `FutureTask` or `ListenableFutureTask` respectively. Also see <<gw-completable-future>> below.
Even though there is a default executor, it is often useful to provide an external one so that you can identify its threads in logs (when using XML, the thread name is based on the executor's bean name):

[source,java]
----
@Bean
public AsyncTaskExecutor exec() {
    SimpleAsyncTaskExecutor simpleAsyncTaskExecutor = new SimpleAsyncTaskExecutor();
    simpleAsyncTaskExecutor.setThreadNamePrefix("exec-");
    return simpleAsyncTaskExecutor;
}

@MessagingGateway(asyncExecutor = "exec")
public interface ExecGateway {

    @Gateway(requestChannel = "gatewayChannel")
    Future<?> doAsync(String foo);

}
----

If you wish to return a different `Future` implementation, you can provide a custom executor, or disable the executor altogether and return the `Future` in the reply message payload from the downstream flow.
To disable the executor, simply set it to `null` in the `GatewayProxyFactoryBean` (`setAsyncTaskExecutor(null)`).
When configuring the gateway with XML, use `async-executor=""`; when configuring using the `@MessagingGateway` annotation, use:

[source,java]
----
@MessagingGateway(asyncExecutor = AnnotationConstants.NULL)
public interface NoExecGateway {

    @Gateway(requestChannel = "gatewayChannel")
    Future<?> doAsync(String foo);

}
----

IMPORTANT: If the return type is a specific concrete `Future` implementation or some other sub-interface that is not supported by the configured executor, the flow will run on the caller's thread and the flow must return the required type in the reply message payload.

[[gw-completable-future]]
===== CompletableFuture

Starting with _version 4.2_, gateway methods can now return `CompletableFuture<?>`.
There are several modes of operation when returning this type:

When an async executor is provided *and* the return type is exactly `CompletableFuture` (not a subclass), the framework
will run the task on the executor and immediately return a `CompletableFuture` to the caller.
`CompletableFuture.supplyAsync(Supplier<U> supplier, Executor executor)` is used to create the future.

When the async executor is explicitly set to `null` and the return type is `CompletableFuture` *or* the return type
is a subclass of `CompletableFuture`, the flow is invoked on the caller's thread.
In this scenario, it is expected that the downstream flow will return a `CompletableFuture` of the appropriate type.

*Usage Scenarios*

[source, java]
----

CompletableFuture<Invoice> order(Order order);
----

[source, xml]
----

<int:gateway service-interface="foo.Service" default-request-channel="orders" />
----

In this scenario, the caller thread returns immediately with a `CompletableFuture<Invoice>` which will be completed
when the downstream flow replies to the gateway (with an `Invoice` object).

[source, java]
----

CompletableFuture<Invoice> order(Order order);
----

[source, xml]
----

<int:gateway service-interface="foo.Service" default-request-channel="orders"
    async-executor="" />
----

In this scenario, the caller thread will return with a CompletableFuture<Invoice> when the downstream flow provides
it as the payload of the reply to the gateway.
Some other process must complete the future when the invoice is ready.

[source, java]
----

MyCompletableFuture<Invoice> order(Order order);
----

[source, xml]
----

<int:gateway service-interface="foo.Service" default-request-channel="orders" />
----

In this scenario, the caller thread will return with a CompletableFuture<Invoice> when the downstream flow provides
it as the payload of the reply to the gateway.
Some other process must complete the future when the invoice is ready.
If `DEBUG` logging is enabled, a log is emitted indicating that the async executor cannot be used for this scenario.


`CompletableFuture` s can be used to perform additional manipulation on the reply, such as:

[source, java]
----

CompletableFuture<String> process(String data);

...

CompletableFuture result = process("foo")
    .thenApply(t -> t.toUpperCase());

...

String out = result.get(10, TimeUnit.SECONDS);
----

===== Reactor Mono

Starting with _version 5.0_, the `GatewayProxyFactoryBean` allows the use of the Project Reactor with gateway interface methods, utilizing a https://github.com/reactor/reactor-core[`Mono<T>`] return type.
The internal `AsyncInvocationTask` is wrapped in a `Mono.fromCallable()`.

A `Mono` can be used to retrieve the result later (similar to a `Future<?>`) or you can consume from it with the dispatcher invoking your `Consumer` when the result is returned to the gateway.

IMPORTANT: The `Mono` isn't _flushed_ immediately by the framework.
Hence the underlying message flow won't be started before the gateway method returns (as it is with `Future<?>` `Executor` task).
The flow will be started when the `Mono` is _subscribed_.
Alternatively, the `Mono` (being a *Composable*) might be a part of Reactor stream, when the `subscribe()` is related to the entire `Flux`.
For example:

[source,java]
----
@MessagingGateway
public static interface TestGateway {

	@Gateway(requestChannel = "promiseChannel")
	Mono<Integer> multiply(Integer value);

	}

	    ...

	@ServiceActivator(inputChannel = "promiseChannel")
	public Integer multiply(Integer value) {
			return value * 2;
	}

		...

    Flux.just("1", "2", "3", "4", "5")
            .map(Integer::parseInt)
            .flatMap(this.testGateway::multiply)
            .collectList()
            .subscribe(integers -> ...);

----

Another example is a simple callback scenario:
[source,java]
----
Mono<Invoice> mono = service.process(myOrder);

mono.subscribe(invoice -> handleInvoice(invoice));
----

The calling thread continues, with `handleInvoice()` being called when the flow completes.

[[gateway-no-response]]
==== Gateway behavior when no response arrives

As it was explained earlier, the Gateway provides a convenient way of interacting with a Messaging system via POJO method invocations, but realizing that a typical method invocation, which is generally expected to always return (even with an Exception), might not always map one-to-one to message exchanges (e.g., a reply message might not arrive - which is equivalent to a method not returning).
It is important to go over several scenarios especially in the Sync Gateway case and understand the default behavior of the Gateway and how to deal with these scenarios to make the Sync Gateway behavior more predictable regardless of the outcome of the message flow that was initialed from such Gateway.

There are certain attributes that could be configured to make Sync Gateway behavior more predictable, but some of them might not always work as you might have expected.
One of them is _reply-timeout_ (at the method level or _default-reply-timeout_ at the gateway level).
So, lets look at the _reply-timeout_ attribute and see how it can/can't influence the behavior of the Sync Gateway in various scenarios.
We will look at single-threaded scenario (all components downstream are connected via Direct Channel) and multi-threaded scenarios (e.g., somewhere downstream you may have Pollable or Executor Channel which breaks single-thread boundary)

_Long running process downstream_

_Sync Gateway - single-threaded_.
If a component downstream is still running (e.g., infinite loop or a very slow service), then setting a _reply-timeout_ has no effect and the Gateway method call will not return until such downstream service exits (via return or exception).
_Sync Gateway - multi-threaded_.
If a component downstream is still running (e.g., infinite loop or a very slow service), in a multi-threaded message flow setting the _reply-timeout_ will have an effect by allowing gateway method invocation to return once the timeout has been reached, since the `GatewayProxyFactoryBean`  will simply poll on the reply channel waiting for a message until the timeout expires.
However it could result in a 'null' return from the Gateway method if the timeout has been reached before the actual reply was produced. It is also important to understand that the reply message (if produced) will be sent to a reply channel after the Gateway method invocation might have returned, so you must be aware of that and design your flow with this in mind.

_Downstream component returns 'null'_

_Sync Gateway - single-threaded_.
If a component downstream returns 'null' and no _reply-timeout_ has been configured, the Gateway method call will hang indefinitely unless: a) a _reply-timeout_ has been configured or b) the _requires-reply_ attribute has been set on the downstream component (e.g., service-activator) that might return 'null'.
In this case, an Exception would be thrown and propagated to the Gateway._Sync Gateway - multi-threaded_.
Behavior is the same as above.

_Downstream component return signature is 'void' while Gateway method signature is non-void_

_Sync Gateway - single-threaded_.
If a component downstream returns 'void' and no _reply-timeout_ has been configured, the Gateway method call will hang indefinitely unless a _reply-timeout_ has been configured  _Sync Gateway - multi-threaded_ Behavior is the same as above.

_Downstream component results in Runtime Exception (regardless of the method signature)_

_Sync Gateway - single-threaded_.
If a component downstream throws a Runtime Exception, such exception will be propagated via an Error Message back to the gateway and re-thrown.
_Sync Gateway - multi-threaded_ Behavior is the same as above.

IMPORTANT: It is also important to understand that by default _reply-timeout_ is unbounded* which means that if not explicitly set there are several scenarios (described above) where your Gateway method invocation might hang indefinitely.
So, make sure you analyze your flow and if there is even a remote possibility of one of these scenarios to occur, set the _reply-timeout_ attribute to a 'safe' value or, even better, set the _requires-reply_ attribute of the downstream component to 'true' to ensure a timely response as produced by the throwing of an Exception as soon as that downstream component does return null internally.
But also, realize that there are some scenarios (see the very first one) where _reply-timeout_ will not help.
That means it is also important to analyze your message flow and decide when to use a Sync Gateway vs an Async Gateway.
As you've seen the latter case is simply a matter of defining Gateway methods that return Future instances.
Then, you are guaranteed to receive that return value, and you will have more granular control over the results of the invocation.Also, when dealing with a Router you should remember that setting the _resolution-required_ attribute to 'true' will result in an Exception thrown by the router if it can not resolve a particular channel.
Likewise, when dealing with a Filter, you can set the _throw-exception-on-rejection_ attribute.
In both of these cases, the resulting flow will behave like that containing a service-activator with the 'requires-reply' attribute.
In other words, it will help to ensure a timely response from the Gateway method invocation.

NOTE: * _reply-timeout_ is unbounded for _<gateway/>_ elements (created by the GatewayProxyFactoryBean).
Inbound gateways for external integration (ws, http, etc.) share many characteristics and attributes with these gateways.
However, for those inbound gateways, the default _reply-timeout_ is 1000 milliseconds (1 second).
If a downstream async hand-off is made to another thread, you may need to increase this attribute to allow enough time for the flow to complete before the gateway times out.

IMPORTANT: It is important to understand that the timer starts when the thread returns to the gateway, i.e. when the
flow completes or a message is handed off to another thread.
At that time, the calling thread starts waiting for the reply.
If the flow was completely synchronous, the reply will be immediately available; for asynchronous flows, the thread
will wait for up to this time.

Also see <<java-dsl-gateway>> in the Java DSL chapter for options to define gateways via `IntegrationFlows`.
