:toc!:

include::./index-header.adoc[]

ifdef::backend-html5[]
*{revnumber}*

NOTE: This documentation is also available as single searchable link:index-single.html[html] and link:../pdf/spring-integration-reference.pdf[pdf] documents.
endif::[]

ifdef::backend-pdf[]
NOTE: This documentation is also available as https://docs.spring.io/spring-integration/docs/current/reference/html/index.html[multiple (faster to load) HTML pages] and as a single https://docs.spring.io/spring-integration/docs/current/reference/html/index-single.html[(more easily searchable) HTML file].
endif::[]

Welcome to the Spring Integration reference documentation!

[horizontal]
<<./preface.adoc#preface,Preface>> :: General project info, conventions
<<./whats-new.adoc#whats-new,What's New>> :: Features and changes made in the current version
<<./overview.adoc#spring-integration-introduction,Overview>> :: Introduction to EIP and its implementation in the project
<<./core.adoc#spring-integration-core-messaging,Core Messaging>> :: Main project abstractions and components
<<./message.adoc#message,Message>> :: Details about the message abstraction implementations
<<./message-routing.adoc#messaging-routing-chapter,Message Routing>> :: main EIP components: router, splitter, aggregator, filter etc.
<<./message-transformation.adoc#messaging-transformation-chapter,Message Transformation>> :: Transformer, content enricher, claim check, codec
<<./messaging-endpoints.adoc#messaging-endpoints-chapter,Messaging Endpoints>> :: Consumer endpoints, service activator, gateway, scripting, AOP aspects etc.
<<./dsl.adoc#java-dsl,Java DSL>> :: Details about Java DSL for EIP
<<./groovy-dsl.adoc#groovy-dsl,Groovy DSL>> :: Details about Groovy DSL for EIP
<<./kotlin-dsl.adoc#kotlin-dsl,Kotlin DSL>> :: Details about Kotlin DSL for EIP
<<./system-management.adoc#system-management-chapter,System Management>> :: Message store, control bus, integration graph, metrics, JMX
<<./reactive-streams.adoc#reactive-streams,Reactive Streams Support>> :: Details about Reactive Streams support: message channels, channel adapters etc.
<<./native-aot.adoc#native-images-support,Native Images Support>> :: GraalVM native images and Spring AOT support

[horizontal]
**Integration Endpoints** ::

[horizontal]
<<./endpoint-summary.adoc#spring-integration-endpoints,Integration Endpoint Summary>> :: Protocol-specific channel adapters and gateways summary
<<./amqp.adoc#amqp,AMQP Support>> :: AMQP channels, adapters and gateways
<<./camel.adoc#camel,Apache Camel Support>> :: Apache Camel channel adapters and gateways
<<./cassandra.adoc#cassandra,Apache Cassandra Support>> :: Apache Cassandra channel adapters
<<./debezium.adoc#debezium,Debezium CDC Support>> :: Debezium channel adapters
<<./event.adoc#applicationevent,Spring `ApplicationEvent` Support>> :: Handling and consuming Spring application events with channel adapters
<<./feed.adoc#feed,Feed Adapter>> :: RSS and Atom channel adapters
<<./file.adoc#files,File Support>> :: Channel adapters and gateways for file system support
<<./ftp.adoc#ftp,FTP/FTPS Adapters>> :: Channel adapters and gateways for FTP protocol
<<./graphql.adoc#graphql,GraphQL Support>> :: Channel adapters for GraphQL
<<./hazelcast.adoc#hazelcast,Hazelcast Support>> :: Channel adapters, gateways and utilities for Hazelcast
<<./http.adoc#http,HTTP Support>> :: Channel adapters and gateways for HTTP communication
<<./jdbc.adoc#jdbc,JDBC Support>> :: Channel adapters and gateways for JDBC, message and metadata stores
<<./jpa.adoc#jpa,JPA Support>> :: Channel adapters and gateways for JPA API
<<./jms.adoc#jms,JMS Support>> :: Channel adapters and gateways for JMS API
<<./jmx.adoc#jmx,JMX Support>> :: Channel adapters for JMX interaction, integration-specific MBean exporter
<<./kafka.adoc#kafka,Apache Kafka Support>> :: Channels, adapters and gateways for Apache Kafka
<<./mail.adoc#mail,Mail Support>> :: Channel adapters for Java Mail API
<<./mongodb.adoc#mongodb,MongoDb Support>> :: Channels, adapters, gateways and message store for MongoDb
<<./mqtt.adoc#mqtt,MQTT Support>> :: Channel adapters for MQTT protocol
<<./r2dbc.adoc#r2dbc,R2DBC Support>> :: Channel adapters for R2DBC API
<<./redis.adoc#redis,Redis Support>> ::  Channels, adapters, gateways and message store for Redis
<<./resource.adoc#resource,Resource Support>> :: Spring resource channel adapters
<<./rsocket.adoc#rsocket,RSocket Support>> :: Channel adapters for RSocket protocol
<<./sftp.adoc#sftp,SFTP Adapters>> :: Channel adapters and gateways for FTP protocol
<<./smb.adoc#smb,SMB Support>> :: Channel adapters and gateways for SMB protocol
<<./stomp.adoc#stomp,STOMP Support>> :: Channel adapters and gateways for STOMP protocol
<<./stream.adoc#stream,Stream Support>> :: Channel adapters for Java IO stream API
<<./syslog.adoc#syslog,Syslog Support>> :: Channel adapters for Syslog protocol
<<./ip.adoc#ip,TCP and UDP Support>> :: Channel adapters and gateways for TCP and UDP protocols
<<./webflux.adoc#webflux,WebFlux Support>> :: Channel adapters and gateways for WebFlux API
<<./web-sockets.adoc#web-sockets,WebSockets Support>> :: Channel adapters for WebSockets protocol
<<./ws.adoc#ws,Web Services Support>> :: Channel adapters for SOAP protocol
<<./xml.adoc#xml,XML Support - Dealing with XML Payloads>> :: Channel adapters and transformers for XML API, xPath
<<./xmpp.adoc#xmpp,XMPP Support>> :: Channel adapters for XMPP protocol
<<./zeromq.adoc#zeromq,ZeroMQ Support>> :: Channels and adapters for ZeroMQ protocol
<<./zookeeper.adoc#zookeeper,Zookeeper Support>> :: Channel adapters for Zookeeper and Curator API

[horizontal]
**Appendices** ::

[horizontal]
<<./error-handling.adoc#error-handling,Error Handling>> :: Overview of error handling approaches in Spring Integration
<<./spel.adoc#spel,Spring Expression Language (SpEL)>> :: Details about SpEL support
<<./message-publishing.adoc#message-publishing,Message Publishing>> :: The Publisher annotation etc.
<<./transactions.adoc#transactions,Transaction Support>> :: Overview of transactions support in Spring Integration
<<./security.adoc#security,Security in Spring Integration>> :: Securing Spring Integration flows
<<./configuration.adoc#configuration,Configuration>> :: Messaging annotations, task scheduler, global properties, message mapping
<<./testing.adoc#testing,Testing support>> :: Test utilities, Integration mocks and testing framework
<<./samples.adoc#samples,Spring Integration Samples>> :: The samples dedicated project
<<./resources.adoc#resources,Additional Resources>> :: Other resources related to project
<<./history.adoc#history,Change History>> :: The changes made in the project over time
