[[jmx]]
=== JMX Support

Spring Integration provides _Channel Adapters_ for receiving and publishing JMX Notifications.
There is also an_Inbound Channel Adapter_ for polling JMX MBean attribute values, and an _Outbound Channel Adapter_ for invoking JMX MBean operations.

[[jmx-notification-listening-channel-adapter]]
==== Notification Listening Channel Adapter

The _Notification-listening Channel Adapter_ requires a JMX ObjectName for the MBean that publishes notifications to which this listener should be registered.
A very simple configuration might look like this:

[source,xml]
----
<int-jmx:notification-listening-channel-adapter id="adapter"
    channel="channel"
    object-name="example.domain:name=publisher"/>
----

TIP: The _notification-listening-channel-adapter_ registers with an `MBeanServer` at startup, and the default bean name is _mbeanServer_ which happens to be the same bean name generated when using Spring's _<context:mbean-server/>_ element.
If you need to use a different name, be sure to include the_mbean-server_ attribute.

The adapter can also accept a reference to a `NotificationFilter` and a _handback_ Object to provide some context that is passed back with each Notification.
Both of those attributes are optional.
Extending the above example to include those attributes as well as an explicit `MBeanServer` bean name would produce the following:

[source,xml]
----
<int-jmx:notification-listening-channel-adapter id="adapter"
    channel="channel"
    mbean-server="someServer"
    object-name="example.domain:name=somePublisher"
    notification-filter="notificationFilter"
    handback="myHandback"/>
----

The _Notification-listening Channel Adapter_ is event-driven and registered with the `MBeanServer` directly.
It does not require any poller configuration.

[NOTE]
=====
For this component only, the _object-name_ attribute can contain an ObjectName pattern (e.g.
"org.foo:type=Bar,name=*") and the adapter will receive notifications from all MBeans with ObjectNames that match the pattern.
In addition, the _object-name_ attribute can contain a SpEL reference to a <util:list/> of ObjectName patterns:
[source,xml]
----
<jmx:notification-listening-channel-adapter id="manyNotificationsAdapter"
    channel="manyNotificationsChannel"
    object-name="#{patterns}"/>

<util:list id="patterns">
    <value>org.foo:type=Foo,name=*</value>
    <value>org.foo:type=Bar,name=*</value>
</util:list>
----

The names of the located MBean(s) will be logged when DEBUG level logging is enabled.
=====

[[jmx-notification-publishing-channel-adapter]]
==== Notification Publishing Channel Adapter

The _Notification-publishing Channel Adapter_ is relatively simple.
It only requires a JMX ObjectName in its configuration as shown below.

[source,xml]
----
<context:mbean-export/>

<int-jmx:notification-publishing-channel-adapter id="adapter"
    channel="channel"
    object-name="example.domain:name=publisher"/>
----

It does also require that an `MBeanExporter` be present in the context.
That is why the _<context:mbean-export/>_ element is shown above as well.

When Messages are sent to the channel for this adapter, the Notification is created from the Message content.
If the payload is a String it will be passed as the _message_ text for the Notification.
Any other payload type will be passed as the _userData_ of the Notification.

JMX Notifications also have a _type_, and it should be a dot-delimited String.
There are two ways to provide the _type_.
Precedence will always be given to a Message header value associated with the `JmxHeaders.NOTIFICATION_TYPE` key.
On the other hand, you can rely on a fallback _default-notification-type_ attribute provided in the configuration.

[source,xml]
----
<context:mbean-export/>

<int-jmx:notification-publishing-channel-adapter id="adapter"
    channel="channel"
    object-name="example.domain:name=publisher"
    default-notification-type="some.default.type"/>
----

[[jmx-attribute-polling-channel-adapter]]
==== Attribute Polling Channel Adapter

The _Attribute Polling Channel Adapter_ is useful when you have a requirement, to periodically check on some value that is available through an MBean as a managed attribute.
The poller can be configured in the same way as any other polling adapter in Spring Integration (or it's possible to rely on the default poller).
The _object-name_ and _attribute-name_ are required.
An MBeanServer reference is also required, but it will automatically check for a bean named _mbeanServer_ by default, just like the _Notification-listening Channel Adapter_ described above.

[source,xml]
----
<int-jmx:attribute-polling-channel-adapter id="adapter"
    channel="channel"
    object-name="example.domain:name=someService"
    attribute-name="InvocationCount">
        <int:poller max-messages-per-poll="1" fixed-rate="5000"/>
</int-jmx:attribute-polling-channel-adapter>
----

[[tree-polling-channel-adapter]]
==== Tree Polling Channel Adapter

The _Tree Polling Channel Adapter_ queries the JMX MBean tree and sends a message with a payload that is the graph of objects that matches the query.
By default the MBeans are mapped to primitives and simple Objects like Map, List and arrays - permitting simple transformation, for example, to JSON.
An MBeanServer reference is also required, but it will automatically check for a bean named _mbeanServer_ by default, just like the _Notification-listening Channel Adapter_ described above.
A basic configuration would be:

[source,xml]
----
<int-jmx:tree-polling-channel-adapter id="adapter"
    channel="channel"
    query-name="example.domain:type=*">
        <int:poller max-messages-per-poll="1" fixed-rate="5000"/>
</int-jmx:tree-polling-channel-adapter>
----

This will include all attributes on the MBeans selected.
You can filter the attributes by providing an `MBeanObjectConverter` that has an appropriate filter configured.
The converter can be provided as a reference to a bean definition using the `converter` attribute, or as an inner <bean/> definition.
A `DefaultMBeanObjectConverter` is provided which can take a `MBeanAttributeFilter` in its constructor argument.

Two standard filters are provided; the `NamedFieldsMBeanAttributeFilter` allows you to specify a list of attributes to include and the `NotNamedFieldsMBeanAttributeFilter` allows you to specify a list of attributes to exclude.
You can also implement your own filter

[[jmx-operation-invoking-channel-adapter]]
==== Operation Invoking Channel Adapter

The _operation-invoking-channel-adapter_ enables Message-driven invocation of any managed operation exposed by an MBean.
Each invocation requires the operation name to be invoked and the ObjectName of the target MBean.
Both of these must be explicitly provided via adapter configuration:

[source,xml]
----
<int-jmx:operation-invoking-channel-adapter id="adapter"
    object-name="example.domain:name=TestBean"
    operation-name="ping"/>
----

Then the adapter only needs to be able to discover the _mbeanServer_ bean.
If a different bean name is required, then provide the _mbean-server_ attribute with a reference.

The payload of the Message will be mapped to the parameters of the operation, if any.
A Map-typed payload with String keys is treated as name/value pairs, whereas a List or array would be passed as a simple argument list (with no explicit parameter names).
If the operation requires a single parameter value, then the payload can represent that single value, and if the operation requires no parameters, then the payload would be ignored.

If you want to expose a channel for a single common operation to be invoked by Messages that need not contain headers, then that option works well.

[[jmx-operation-invoking-outbound-gateway]]
==== Operation Invoking Outbound Gateway

Similar to the _operation-invoking-channel-adapter_ Spring Integration also provides a _operation-invoking-outbound-gateway_, which could be used when dealing with non-void operations and a return value is required.
Such return value will be sent as message payload to the _reply-channel_ specified by this Gateway.

[source,xml]
----
<int-jmx:operation-invoking-outbound-gateway request-channel="requestChannel"
   reply-channel="replyChannel"
   object-name="o.s.i.jmx.config:type=TestBean,name=testBeanGateway"
   operation-name="testWithReturn"/>
----

If the _reply-channel_ attribute is not provided, the reply message will be sent to the channel that is identified by the `IntegrationMessageHeaderAccessor.REPLY_CHANNEL` header.
That header is typically auto-created by the entry point into a message flow, such as any _Gateway_ component.
However, if the message flow was started by manually creating a Spring Integration Message and sending it directly to a _Channel_, then you must specify the message header explicitly or use the provided _reply-channel_ attribute.

[[jmx-mbean-exporter]]
==== MBean Exporter

Spring Integration components themselves may be exposed as MBeans when the `IntegrationMBeanExporter` is configured.
To create an instance of the `IntegrationMBeanExporter`, define a bean and provide a reference to an `MBeanServer` and a domain name (if desired).
The domain can be left out, in which case the default domain is _org.springframework.integration_.

[source,xml]
----
<int-jmx:mbean-export id="integrationMBeanExporter"
            default-domain="my.company.domain" server="mbeanServer"/>

<bean id="mbeanServer" class="org.springframework.jmx.support.MBeanServerFactoryBean">
    <property name="locateExistingServerIfPossible" value="true"/>
</bean>
----

[IMPORTANT]
=====
The MBean exporter is orthogonal to the one provided in Spring core - it registers message channels and message handlers, but not itself.
You can expose the exporter itself, and certain other components in Spring Integration, using the standard `<context:mbean-export/>` tag.
The exporter has a some metrics attached to it, for instance a count of the number of active handlers and the number of queued messages.

It also has a useful operation, as discussed in <<jmx-mbean-shutdown>>.
=====

Starting with _Spring Integration 4.0_ the `@EnableIntegrationMBeanExport` annotation has been introduced for convenient configuration of a default (`integrationMbeanExporter`) bean of type `IntegrationMBeanExporter` with several useful options at the `@Configuration` class level.
For example:
[source,java]
----
@Configuration
@EnableIntegration
@EnableIntegrationMBeanExport(server = "mbeanServer", managedComponents = "input")
public class ContextConfiguration {

	@Bean
	public MBeanServerFactoryBean mbeanServer() {
		return new MBeanServerFactoryBean();
	}
}
----

If there is a need to provide more options, or have several `IntegrationMBeanExporter` beans e.g.
for different MBean Servers, or to avoid conflicts with the standard Spring `MBeanExporter` (e.g.
via `@EnableMBeanExport`), you can simply configure an `IntegrationMBeanExporter` as a generic bean.

[[jmx-mbean-features]]
===== MBean ObjectNames

All the `MessageChannel`, `MessageHandler` and `MessageSource` instances in the application are wrapped by the MBean exporter to provide management and monitoring features.
The generated JMX object names for each component type are listed in the table below:

.MBean ObjectNames

[cols="1,3l", options="header"]
|===
| Component Type
| ObjectName

| MessageChannel
| o.s.i:type=MessageChannel,name=<channelName>

| MessageSource
| o.s.i:type=MessageSource,name=<channelName>,bean=<source>

| MessageHandler
| o.s.i:type=MessageSource,name=<channelName>,bean=<source>
|===

The _bean_ attribute in the object names for sources and handlers takes one of the values in the table below:

.bean ObjectName Part


[cols="1,3", options="header"]
|===
| Bean Value
| Description

| endpoint
| The bean name of the enclosing endpoint (e.g.
<service-activator>) if there is one

| anonymous
| An indication that the enclosing endpoint didn't have a user-specified bean name, so the JMX name is the input channel name

| internal
| For well-known Spring Integration default  components

| handler/source
| None of the above: fallback to the `toString()` of the object being monitored (handler or source)

|===

Custom elements can be appended to the object name by providing a reference to a `Properties` object in the `object-name-static-properties` attribute.

Also, since _Spring Integration 3.0_, you can use a custom http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jmx/export/naming/ObjectNamingStrategy.html[ObjectNamingStrategy] using the `object-naming-strategy` attribute.
This permits greater control over the naming of the MBeans.
For example, to group all Integration MBeans under an 'Integration' type.
A simple custom naming strategy implementation might be:

[source,java]
----
public class Namer implements ObjectNamingStrategy {

	private final ObjectNamingStrategy realNamer = new KeyNamingStrategy();
	@Override
	public ObjectName getObjectName(Object managedBean, String beanKey) throws MalformedObjectNameException {
		String actualBeanKey = beanKey.replace("type=", "type=Integration,componentType=");
		return realNamer.getObjectName(managedBean, actualBeanKey);
	}

}
----

The `beanKey` argument is a String containing the standard object name beginning with the `default-domain` and including any additional static properties.
This example simply moves the standard `type` part to `componentType` and sets the `type` to 'Integration', enabling selection of all Integration MBeans in one query:`"my.domain:type=Integration,*`.
This also groups the beans under one tree entry under the domain in tools like VisualVM.

NOTE: The default naming strategy is a http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jmx/export/naming/MetadataNamingStrategy.html[MetadataNamingStrategy].
The exporter propagates the `default-domain` to that object to allow it to generate a fallback object name if parsing of the bean key fails.
If your custom naming strategy is a `MetadataNamingStrategy` (or subclass), the exporter will *not* propagate the `default-domain`; you will need to configure it on your strategy bean.

[[jmx-42-improvements]]
===== JMX Improvements

_Version 4.2_ introduced some important improvements, representing a fairly major overhaul to the JMX support in the framework.
These resulted in a significant performance improvement of the JMX statistics collection and much more control thereof, but has some implications for user code in a few specific (uncommon) situations.
These changes are detailed below, with a *caution* where necessary.

* *Metrics Capture*

Previously, `MessageSource`, `MessageChannel` and `MessageHandler` metrics were captured by wrapping the object in a JDK dynamic proxy to intercept appropriate method calls and capture the statistics.
The proxy was added when an integration MBean exporter was declared in the context.

Now, the statistics are captured by the beans themselves; see <<metrics-management>> for more information.

WARNING: This change means that you no longer automatically get an MBean or statistics for custom `MessageHandler` implementations, unless those custom handlers extend `AbstractMessageHandler`.
The simplest way to resolve this is to extend `AbstractMessageHandler`.
If that's not possible, or desired, another work-around is to implement the `MessageHandlerMetrics` interface.
For convenience, a `DefaultMessageHandlerMetrics` is provided to capture and report statistics.
Invoke the `beforeHandle` and `afterHandle` at the appropriate times.
Your `MessageHandlerMetrics` methods can then delegate to this object to obtain each statistic.
Similarly, `MessageSource` implementations must extend `AbstractMessageSource` or implement `MessageSourceMetrics`.
Message sources only capture a count so there is no provided convenience class; simply maintain the count in an `AtomicLong` field.

The removal of the proxy has two additional benefits; 1) stack traces in exceptions are reduced (when JMX is enabled) because the proxy is not on the stack; 2) cases where 2 MBeans were exported for the same bean now only export a single MBean with consolidated attributes/operations (see the MBean consolidation bullet below).


* *Resolution*

`System.nanoTime()` is now used to capture times instead of `System.currentTimeMillis()`.
This may provide more accuracy on some JVMs, espcially when durations of less than 1 millisecond are expected


* *Setting Initial Statistics Collection State*

Previously, when JMX was enabled, all sources, channels, handlers captured statistics.
It is now possible to control whether the statisics are enabled on an individual component.
Further, it is possible to capture simple counts on `MessageChannel` s and `MessageHandler` s instead of the complete time-based statistics.
This can have significant performance implications because you can selectively configure where you need detailed statistics, as well as enable/disable at runtime.

See <<metrics-management>>.

* *@IntegrationManagedResource*

Similar to the `@ManagedResource` annotation, the `@IntegrationManagedResource` marks a class as eligible to be exported as an MBean; however, it will only be exported if there is an `IntegrationMBeanExporter` in the application context.

Certain Spring Integration classes (in the `org.springframework.integration`) package) that were previously annotated with`@ManagedResource` are now annotated with both `@ManagedResource` and `@IntegrationManagedResource`.
This is for backwards compatibility (see the next bullet).
Such MBeans will be exported by any context `MBeanServer`*or* an `IntegrationMBeanExporter` (but not both - if both exporters are present, the bean is exported by the integration exporter if the bean matches a `managed-components` pattern).


* *Consolidated MBeans*

Certain classes within the framework (mapping routers for example) have additional attributes/operations over and above those provided by metrics and `Lifecycle`.
We will use a `Router` as an example here.

Previously, beans of these types were exported as two distinct MBeans:

1) the metrics MBean (with an objectName such as: `intDomain:type=MessageHandler,name=myRouter,bean=endpoint`).
This MBean had metrics attributes and metrics/Lifecycle operations.

2) a second MBean (with an objectName such as:
`ctxDomain:name=org.springframework.integration.config.RouterFactoryBean#0`
`,type=MethodInvokingRouter`)
was exported with the channel mappings attribute and operations.

Now, the attributes and operations are consolidated into a single MBean.
The objectName will depend on the exporter.
If exported by the integration MBean exporter, the objectName will be, for example: `intDomain:type=MessageHandler,name=myRouter,bean=endpoint`.
If exported by another exporter, the objectName will be, for example: `ctxDomain:name=org.springframework.integration.config.RouterFactoryBean#0`
`,type=MethodInvokingRouter`.
There is no difference between these MBeans (aside from the objectName), except that the statistics will *not* be enabled (the attributes will be 0) by exporters other than the integration exporter; statistics can be enabled at runtime using the JMX operations.
When exported by the integration MBean exporter, the initial state can be managed as described above.

WARNING: If you are currently using the second MBean to change, for example, channel mappings, *and* you are using the integration MBean exporter, note that the objectName has changed because of the MBean consolidation.
There is no change if you are not using the integration MBean exporter.


* *MBean Exporter Bean Name Patterns*

Previously, the `managed-components` patterns were inclusive only.
If a bean name matched one of the patterns it would be included.
Now, the pattern can be negated by prefixing it with `!`.
i.e.
`"!foo*, foox"` will match all beans that don't start with `foo`, except `foox`.
Patterns are evaluated left to right and the first match (positive or negative) wins and no further patterns are applied.

WARNING: The addition of this syntax to the pattern causes one possible (although perhaps unlikely) problem.
If you have a bean `"!foo"`*and* you included a pattern `"!foo"` in your MBean exporter's `managed-components` patterns; it will no long match; the pattern will now match all beans *not* named `foo`.
In this case, you can escape the `!` in the pattern with `\`.
The pattern `"\!foo"` means match a bean named `"!foo"`.

* *IntegrationMBeanExporter changes*

The `IntegrationMBeanExporter` no longer implements `SmartLifecycle`; this means that `start()` and `stop()` operations
are no longer available to register/unregister MBeans.
The MBeans are now registered during context initialization and unregistered when the context is destroyed.



[[jmx-mbean-shutdown]]
===== Orderly Shutdown Managed Operation

The MBean exporter provides a JMX operation to shut down the application in an orderly manner, intended for use before terminating the JVM.

[source,java]
----
public void stopActiveComponents(long howLong)

----

Its use and operation are described in <<jmx-shutdown>>.
