[[message-store]]
=== Message Store

Enterprise Integration Patterns (EIP) identifies several patterns that have the capability to buffer messages.
For example, an _Aggregator_ buffers messages until they can be released and a _QueueChannel_ buffers messages until consumers explicitly receive those messages from that channel.
Because of the failures that can occur at any point within your message flow, EIP components that buffer messages also introduce a point where messages could be lost.

To mitigate the risk of losing Messages, EIP defines the http://eaipatterns.com/MessageStore.html[Message Store] pattern which allows EIP components to store _Messages_ typically in some type of persistent store (e.g.
RDBMS).

Spring Integration provides support for the _Message Store_ pattern by a) defining a `org.springframework.integration.store.MessageStore` strategy interface, b) providing several implementations of this interface, and c) exposing a `message-store` attribute on all components that have the capability to buffer messages so that you can inject any instance that implements the `MessageStore` interface.

Details on how to configure a specific _Message Store_ implementation and/or how to inject a `MessageStore` implementation into a specific buffering component are described throughout the manual (see the specific component, such as <<channel-configuration-queuechannel,_QueueChannel_>>, <<aggregator,_Aggregator_>>, <<delayer,_Delayer_>> etc.), but here are a couple of samples to give you an idea:

QueueChannel
[source,xml]
----
<int:channel id="myQueueChannel">
    <int:queue message-store="refToMessageStore"/>
<int:channel>
----

Aggregator
[source,xml]
----
<int:aggregator … message-store="refToMessageStore"/>
----

By default _Messages_ are stored in-memory using `org.springframework.integration.store.SimpleMessageStore`, an implementation of `MessageStore`.
That might be fine for development or simple low-volume environments where the potential loss of non-persistent messages is not a concern.
However, the typical production application will need a more robust option, not only to mitigate the risk of message loss but also to avoid potential out-of-memory errors.
Therefore, we also provide MessageStore implementations for a variety of data-stores.
Below is a complete list of supported implementations:

* <<jdbc-message-store>> - uses RDBMS to store Messages
* <<redis-message-store>> - uses Redis key/value datastore to store Messages
* <<mongodb-message-store>> - uses MongoDB document store to store Messages
* <<gemfire-message-store>> - uses Gemfire distributed cache to store Messages

[IMPORTANT]
=====
However be aware of some limitations while using persistent implementations of the `MessageStore`.

The Message data (payload and headers) is _serialized_ and _deserialized_ using different serialization strategies depending on the implementation of the `MessageStore`.
For example, when using `JdbcMessageStore`, only `Serializable` data is persisted by default.
In this case non-Serializable headers are removed before serialization occurs.
Also be aware of the protocol specific headers that are injected by transport adapters (e.g., FTP, HTTP, JMS etc.).
For example, `<http:inbound-channel-adapter/>` maps HTTP-headers into Message Headers and one of them is an `ArrayList` of non-Serializable `org.springframework.http.MediaType` instances.
However you are able to inject your own implementation of the `Serializer` and/or `Deserializer` strategy interfaces into some `MessageStore` implementations (such as JdbcMessageStore) to change the behaviour of serialization and deserialization.

Special attention must be paid to the headers that represent certain types of data.
For example, if one of the headers contains an instance of some _Spring Bean_, upon deserialization you may end up with a different instance of that bean, which directly affects some of the implicit headers created by the framework (e.g., REPLY_CHANNEL or ERROR_CHANNEL).
Currently they are not serializable, but even if they were, the deserialized channel would not represent the expected instance.

Beginning with _Spring Integration version 3.0_, this issue can be resolved with a header enricher, configured to replace these headers with a name after registering the channel with the `HeaderChannelRegistry`.

Also when configuring a message-flow like this: _gateway -> queue-channel (backed by a persistent Message Store) -> service-activator_ That gateway creates a _Temporary Reply Channel_, and it will be lost by the time the service-activator's poller reads from the queue.
Again, you can use the header enricher to replace the headers with a String representation.

For more information, refer to the <<header-enricher>>.
=====

_Spring Integration 4.0_ introduced two new interfaces `ChannelMessageStore` - to implement operations specific for `QueueChannel` s, `PriorityCapableChannelMessageStore` - to mark `MessageStore` implementation to be used for `PriorityChannel` s and to provide _priority_ order for persisted Messages.
The real behaviour depends on implementation.
The Framework provides these implementations, which can be used as a persistent `MessageStore` for `QueueChannel` and `PriorityChannel`:

* <<redis-cms>>
* <<mongodb-priority-channel-message-store>>
* <<jdbc-message-store-channels>>

[[sms-caution]]
[WARNING]
.Caution with SimpleMessageStore
=====

Starting with _version 4.1_, the `SimpleMessageStore` no longer copies the message group when calling `getMessageGroup()`.
For large message groups, this was a significant performance problem.
4.0.1 introduced a boolean `copyOnGet` allowing this to be controlled.
When used internally by the aggregator, this was set to false to improve performance.
It is now false by default.

Users accessing the group store outside of components such as aggregators, will now get a direct reference to the group being used by the aggregator, instead of a copy.
Manipulation of the group outside of the aggregator may cause unpredictable results.

For this reason, users should not perform such manipulation, or set the `copyOnGet` property to `true`.
=====

[[message-group-factory]]
==== MessageGroupFactory

Starting with _version 4.3_, some `MessageGroupStore` implementations can be injected with a custom
`MessageGroupFactory` strategy to create/customize the `MessageGroup` instances used by the `MessageGroupStore`.
This defaults to a `SimpleMessageGroupFactory` which produces `SimpleMessageGroup` s based on the `GroupType.HASH_SET`
(`LinkedHashSet`) internal collection.
Other possible options are `SYNCHRONISED_SET` and `BLOCKING_QUEUE`, where the last one can be used to reinstate the
previous `SimpleMessageGroup` behavior.
Also the `PERSISTENT` option is available. See the next section for more information.
Starting with __version 5.0.1_, the `LIST` option is also available for use-cases when the order and uniqueness of messages in the group doesn't matter.

[[lazy-load-message-group]]
==== Persistence MessageGroupStore and Lazy-Load

Starting with _version 4.3_, all persistence `MessageGroupStore` s retrieve `MessageGroup` s and their `messages`
from the store with the _Lazy-Load_ manner.
In most cases it is useful for the Correlation `MessageHandler` s (<<aggregator>> and <<resequencer>>),
when it would be an overhead to load entire `MessageGroup` from the store on each correlation operation.

To switch off the lazy-load behavior the `AbstractMessageGroupStore.setLazyLoadMessageGroups(false)` option
can be used from the configuration.

Our performance tests for _lazy-load_ on MongoDB `MessageStore` (<<mongodb-message-store>>) and
`<aggregator>` (<<aggregator>>)
with custom `release-strategy` like:

[source,xml]
----
<int:aggregator input-channel="inputChannel"
                output-channel="outputChannel"
                message-store="mongoStore"
                release-strategy-expression="size() == 1000"/>

----

demonstrate this results for 1000 simple messages:

....
StopWatch 'Lazy-Load Performance': running time (millis) = 38918
-----------------------------------------
ms     %     Task name
-----------------------------------------
02652  007%  Lazy-Load
36266  093%  Eager
....

