[[preface]]
= Preface
[preface]

[[system-requirements]]
== Requirements

This section details the compatible http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java] and http://www.springsource.org/spring-framework[Spring Framework] versions.

[[supported-java-versions]]
=== Compatible Java Versions

For _Spring Integration_ *4.3.x*, the *minimum* compatible Java version is *Java SE 6*.
Older versions of Java are not supported.

_Spring Integration_ *4.3.x* is also compatible with *Java SE 7* as well as *Java SE 8*.

Certain features (such as `Optional<?>` payloads and `CompletableFuture` gateway method return types) require Java 8.

While the jars are compatible with Java 6, Java 8 is required to build the project.
see https://github.com/spring-projects/spring-integration#checking-out-and-building[Checking out and Building].

[[supported-spring-versions]]
=== Compatible Versions of the Spring Framework

_Spring Integration_ *4.3.x* requires _Spring Framework_ *4.3* or later.

[[code-conventions]]
=== Code Conventions

The Spring Framework 2.0 introduced support for namespaces, which simplifies the XML configuration of the application context, and consequently Spring Integration provides broad namespace support.
This reference guide applies the following conventions for all code examples that use namespace support:

The *int* namespace prefix will be used for Spring Integration's core namespace support.
Each Spring Integration adapter type (module) will provide its own namespace, which is configured using the following convention:

*int-* followed by the name of the module, e.g.
*int-twitter*, *int-stream*, …
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:int="http://www.springframework.org/schema/integration"
  xmlns:int-twitter="http://www.springframework.org/schema/integration/twitter"
  xmlns:int-stream="http://www.springframework.org/schema/integration/stream"
  xsi:schemaLocation="
   http://www.springframework.org/schema/beans
   http://www.springframework.org/schema/beans/spring-beans.xsd
   http://www.springframework.org/schema/integration
   http://www.springframework.org/schema/integration/spring-integration.xsd
   http://www.springframework.org/schema/integration/twitter
   http://www.springframework.org/schema/integration/twitter/spring-integration-twitter.xsd
   http://www.springframework.org/schema/integration/stream
   http://www.springframework.org/schema/integration/stream/spring-integration-stream.xsd">
…
</beans>
----

For a detailed explanation regarding Spring Integration's namespace support see _<<configuration-namespace>>_.

NOTE: Please note that the namespace prefix can be freely chosen.
You may even choose not to use any namespace prefixes at all.
Therefore, apply the convention that suits your application needs best.
Be aware, though, that SpringSource Tool Suite™ (STS) uses the same namespace conventions for Spring Integration as used in this reference guide.


== Conventions in this Book

In some cases, to aid formatting, when specifying long fully-qualified class names, we shorten
the package `org.springframework` to `o.s` and `org.springframework.integration` to `o.s.i`, such as with
`o.s.i.transaction.TransactionSynchronizationFactory`.
