[[service-activator]]
=== Service Activator

[[service-activator-introduction]]
==== Introduction

The Service Activator is the endpoint type for connecting any Spring-managed Object to an input channel so that it may play the role of a service.
If the service produces output, it may also be connected to an output channel.
Alternatively, an output producing service may be located at the end of a processing pipeline or message flow in which case, the inbound Message's "replyChannel" header can be used.
This is the default behavior if no output channel is defined and, as with most of the configuration options you'll see here, the same behavior actually applies for most of the other components we have seen.

[[service-activator-namespace]]
==== Configuring Service Activator

To create a Service Activator, use the 'service-activator' element with the 'input-channel' and 'ref' attributes:
[source,xml]
----
<int:service-activator input-channel="exampleChannel" ref="exampleHandler"/>
----

The configuration above selects all methods from the `exampleHandler` which meet one of the Messaging requirements:

- annotated with `@ServiceActivator`;
- is `public`;
- not `void` return if `requiresReply == true`.

The target method for invocation at runtime is selected for each request message by their `payload` type.
Or as a fallback to `Message<?>` type if such a method is present on target class.

Starting with _version 5.0_, one service method can be marked with the `@org.springframework.integration.annotation.Default` as a fallback for all non-matching cases.
This can be useful when using <<content-type-conversion>> with the target method being invoked after conversion.

To delegate to an explicitly defined method of any object, simply add the "method" attribute.

[source,xml]
----
<int:service-activator input-channel="exampleChannel" ref="somePojo" method="someMethod"/>
----

In either case, when the service method returns a non-null value, the endpoint will attempt to send the reply message to an appropriate reply channel.
To determine the reply channel, it will first check if an "output-channel" was provided in the endpoint configuration:
[source,xml]
----
<int:service-activator input-channel="exampleChannel" output-channel="replyChannel"
                       ref="somePojo" method="someMethod"/>
----

If the method returns a result and no "output-channel" is defined, the framework will then check the request Message's `replyChannel` header value.
If that value is available, it will then check its type.
If it is a `MessageChannel`, the reply message will be sent to that channel.
If it is a `String`, then the endpoint will attempt to resolve the channel name to a channel instance.
If the channel cannot be resolved, then a `DestinationResolutionException` will be thrown.
It it can be resolved, the Message will be sent there.
If the request Message doesn't have `replyChannel` header and and  the `reply` object is a `Message`, its `replyChannel` header is consulted for a target destination.
This is the technique used for Request Reply messaging in Spring Integration, and it is also an example of the Return Address pattern.

If your method returns a result, and you want to discard it and end the flow, you should configure the `output-channel` to send to a `NullChannel`.
For convenience, the framework registers one with the name `nullChannel`.
See <<channel-special-channels>> for more information.

The Service Activator is one of those components that is not required to produce a reply message.
If your method returns `null` or has a `void` return type, the Service Activator exits after the method invocation, without any signals.
This behavior can be controlled by the `AbstractReplyProducingMessageHandler.requiresReply` option, also exposed as `requires-reply` when configuring with the XML namespace.
If the flag is set to `true` and the method returns null, a `ReplyRequiredException` is thrown.

The argument in the service method could be either a Message or an arbitrary type.
If the latter, then it will be assumed that it is a Message payload, which will be extracted from the message and injected into such service method.
This is generally the recommended approach as it follows and promotes a POJO model when working with Spring Integration.
Arguments may also have @Header or @Headers annotations as described in <<annotations>>

NOTE: The service method is not required to have any arguments at all, which means you can implement event-style Service Activators, where all you care about is an invocation of the service method, not worrying about the contents of the message.
Think of it as a NULL JMS message.
An example use-case for such an implementation could be a simple counter/monitor of messages deposited on the input channel.

Starting with _version 4.1_ the framework correct converts Message properties (`payload` and `headers`) to the Java 8 `Optional` POJO method parameters:
[source,java]
----
public class MyBean {
    public String computeValue(Optional<String> payload,
               @Header(value="foo", required=false) String foo1,
               @Header(value="foo") Optional<String> foo2) {
        if (payload.isPresent()) {
            String value = payload.get();
            ...
        }
        else {
           ...
       }
    }

}
----

Using a `ref` attribute is generally recommended if the custom Service Activator handler implementation can be reused in other `<service-activator>` definitions.
However if the custom Service Activator handler implementation is only used within a single definition of the `<service-activator>`, you can provide an inner bean definition:
[source,xml]
----
<int:service-activator id="exampleServiceActivator" input-channel="inChannel"
            output-channel = "outChannel" method="foo">
    <beans:bean class="org.foo.ExampleServiceActivator"/>
</int:service-activator>
----

NOTE: Using both the "ref" attribute and an inner handler definition in the same `<service-activator>` configuration is not allowed, as it creates an ambiguous condition and will result in an Exception being thrown.

IMPORTANT: If the "ref" attribute references a bean that extends `AbstractMessageProducingHandler` (such as handlers provided by the framework itself), the configuration is optimized by injecting the output channel into the handler directly.
In this case, each "ref" must be to a separate bean instance (or a `prototype`-scoped bean), or use the inner `<bean/>` configuration type.
If you inadvertently reference the same message handler from multiple beans, you will get a configuration exception.

_Service Activators and the Spring Expression Language (SpEL)_

Since Spring Integration 2.0, Service Activators can also benefit from SpEL (http://static.springsource.org/spring/docs/3.0.x/spring-framework-reference/html/expressions.html).

For example, you may now invoke any bean method without pointing to the bean via a `ref` attribute or including it as an inner bean definition.
For example:
[source,xml]
----
<int:service-activator input-channel="in" output-channel="out"
	expression="@accountService.processAccount(payload, headers.accountId)"/>

	<bean id="accountService" class="foo.bar.Account"/>
----

In the above configuration instead of injecting 'accountService' using a `ref` or as an inner bean, we are simply using SpEL's `@beanId` notation and invoking a method which takes a type compatible with Message payload.
We are also passing a header value.
As you can see, any valid SpEL expression can be evaluated against any content in the Message.
For simple scenarios your _Service Activators_ do not even have to reference a bean if all logic can be encapsulated by such an expression.
[source,xml]
----
<int:service-activator input-channel="in" output-channel="out" expression="payload * 2"/>
----

In the above configuration our service logic is to simply multiply the payload value by 2, and SpEL lets us handle it relatively easy.

See <<java-dsl-handle>> in Java DSL chapter for more information about configuring Service Activator.

[[async-service-activator]]
==== Asynchronous Service Activator

The service activator is invoked by the calling thread; this would be some upstream thread if the input channel is a
`SubscribableChannel`, or a poller thread for a `PollableChannel`.
If the service returns a `ListenableFuture<?>` the default action is to send that as the payload of the message sent
to the output (or reply) channel.
Starting with _version 4.3_, you can now set the `async` attribute to true (`setAsync(true)` when using
Java configuration).
If the service returns a `ListenableFuture<?>` when this is true, the calling thread is released immediately, and the
reply message is sent on the thread (from within your service) that completes the future.
This is particularly advantageous for long-running services using a `PollableChannel` because the poller thread is
freed up to perform other services within the framework.

If the service completes the future with an `Exception`, normal error processing will occur - an `ErrorMessage` is
sent to the `errorChannel` message header, if present or otherwise to the default `errorChannel` (if available).
