[[whats-new]]

== What's New in Spring Integration 5.2?

If you are interested in more details, see the Issue Tracker tickets that were resolved as part of the 5.2 development process.

[[x5.2-new-components]]
=== New Components

[[x5.2-rateLimitAdvice]]
=== Rate Limit Advice Support

The `RateLimiterRequestHandlerAdvice` is now available for limiting requests rate on handlers.
See <<rate-limiter-advice>> for more information.

[[x5.2-general]]
=== General Changes

[[x5.2-amqp]]
==== AMQP Changes

The outbound endpoints can now be configured to synthesize a "nack" if no publisher confirm is received within a timeout.
See <<amqp-outbound-endpoints>> for more information.

[[x5.2-file]]
==== File Changes

Some improvements to filtering remote files have been made.
See <<remote-persistent-flf>> for more information.

[[x5.2-tcp]]
==== TCP Changes

The length header used by the `ByteArrayLengthHeaderSerializer` can now include the length of the header in addition to the payload.
See <<tcp-codecs>> for more information.
