[[whats-new]]

== What's New in Spring Integration 5.2?

If you are interested in more details, see the Issue Tracker tickets that were resolved as part of the 5.2 development process.

[[x5.2-new-components]]
=== New Components

[[x5.2-rateLimitAdvice]]
=== Rate Limit Advice Support

The `RateLimiterRequestHandlerAdvice` is now available for limiting requests rate on handlers.
See <<rate-limiter-advice>> for more information.

[[x5.2-cacheAdvice]]
=== Caching Advice Support

The `CacheRequestHandlerAdvice` is now available for caching request results on handlers.
See <<cache-advice>> for more information.

[[x5.2-kotlinScripts]]
=== Kotlin Scripts Support

The JSR223 scripting module now includes a support for Kotlin scripts.
See <<scripting>> for more information.

[[x5.2-general]]
=== General Changes

The `JsonToObjectTransformer` now supports generics for the target object to deserialize into.
See <<json-transformers>> for more information.

RThe `splitter` now supports a `discardChannel` configuration option.
See <<splitter>> for more information.

[[x5.2-amqp]]
==== AMQP Changes

The outbound endpoints can now be configured to synthesize a "nack" if no publisher confirm is received within a timeout.
See <<amqp-outbound-endpoints>> for more information.

[[x5.2-file]]
==== File Changes

Some improvements to filtering remote files have been made.
See <<remote-persistent-flf>> for more information.

[[x5.2-tcp]]
==== TCP Changes

The length header used by the `ByteArrayLengthHeaderSerializer` can now include the length of the header in addition to the payload.
See <<tcp-codecs>> for more information.

When using a `TcpNioServerConnectionFactory`, priority is now given to accepting new connections over reading from existing connections, but it is configurable.
See <<note-nio>> for more information.

[[x5.2-mail]]
==== Mail Changes

The `AbstractMailReceiver` has now an `autoCloseFolder` option (`true` by default), to disable an automatic folder close after a fetch, but populate `IntegrationMessageHeaderAccessor.CLOSEABLE_RESOURCE` header instead for downstream interaction.
See <<mail-inbound>> for more information.

[[x5.2-webflux]]
==== WebFlux Changes

The `WebFluxRequestExecutingMessageHandler` now supports a `Publisher`, `Resource` and `MultiValueMap` as a request message `payload`.
See <<webflux>> for more information.
