[[whats-new]]
== What's new in Spring Integration 4.3?

This chapter provides an overview of the new features and improvements that have been introduced with Spring
Integration 4.3.
If you are interested in more details, please see the Issue Tracker tickets that were resolved as part of the 4.3
development process.

[[x4.3-new-components]]
=== New Components

==== MessageGroupFactory

The new `MessageGroupFactory` strategy has been introduced to allow a control over `MessageGroup` instances
in the `MessageGroupStore` logic.
The `SimpleMessageGroupFactory` is provided for the `SimpleMessageGroup` with the `GroupType.HASH_SET` as default
factory for the particular `MessageGroupStore` implementations.
See <<message-store>> for more information.


[[x4.3-general]]
=== General Changes

==== Outbound Gateway within Chain

Previously, it was possible to specify a `reply-channel` on an outbound gateway within a chain.
It was completely ignored; the gateway's reply goes to the next chain element, or to the chain's output channel
if the gateway is the last element.
This condition is now detected and disallowed.
If you have such configuration, simply remove the `reply-channel`.

==== Mail Changes

The customizable `userFlag` added in 4.2.2 to provide customization of the flag used to denote that the mail has been
seen is now available using the XML namespace.
See <<imap-seen>> for more information.

==== JMS Changes

The `DefaultJmsHeaderMapper` now maps the standard `correlationId` header as a message property by invoking its
`toString()` method.
See <<jms-header-mapping>> for more information.

==== Aggregator Changes

There is a change in behavior when a POJO aggregator releases a collection of `Message<?>` objects; this is rare but if
your application does that, you will need to make a small change to your POJO. See this <<agg-message-collection>> note
for more information.

==== TCP Changes

A new `TcpConnectionServerListeningEvent` is emitted when a server connection factory is started.
See <<tcp-events>> for more information.

The `destination-expression` and `socket-expression` are now available for the `<int-ip:udp-outbound-channel-adapter>`.
See <<udp-adapters>> for more information.

==== File Changes

The generated file name for the `FileWritingMessageHandler` can represent _sub-path_ to save the desired directory
structure for file in the target directory.
See <<file-writing-file-names>> for more information.

==== AMQP Changes

The outbound endpoints now support a `RabbitTemplate` configured with a `ContentTypeDelegatingMessageConverter` such
that the converter can be chosen based on the message content type.
See <<content-type-conversion-outbound>> for more information.
