[[whats-new]]

== What's new in Spring Integration 5.1?

This chapter provides an overview of the new features and improvements that have been introduced with Spring
Integration `5.1`.
If you are interested in more details, please see the Issue Tracker tickets that were resolved as part of the 5.1 development process.

[[x5.1-new-components]]
=== New Components

==== AmqpDedicatedChannelAdvice

See <<amqp-strict-ordering>>.

[[x5.1-general]]
=== General Changes

==== Java DSL

The `IntegrationFlowContext` is now an interface and `IntegrationFlowRegistration` is an inner interface of the `IntegrationFlowContext`.

==== Dispatcher Exceptions

Exceptions caught and re-thrown by `AbstractDispatcher` are now more consistent:

- A `MessagingException` of any kind, with a `failedMessage` property, is re-thrown unchanged
- All other exceptions are wrapped in a `MessageDeliveryException` with the `failedMessage` property set

Previously:

- A `MessagingException` of any kind, with a `failedMessage` property, was re-thrown unchanged
- A `MessagingException`, with no `failedMessage` property, was wrapped in a `MessagingException` with the `failedMessage` property set
- Other `RuntimeException` s were re-thrown unchanged
- Checked exceptions were wrapped in a `MessageDeliveryException` with the `failedMessage` property set

==== Global Channel Interceptors

Global channel interceptors are now applied to channels registered dynamically - such as via the `IntegrationFlowContext` when using the Java DSL, or beans that are initialized using `beanFactory.initializeBean()`.
Previously, interceptors were not applied when beans were created after the application context was refreshed.

==== ObjectToJsonTransformer

A new `ResultType.BYTES` mode is introduced for the `ObjectToJsonTransformer`.

See <<json-transformers>> for more information.

==== Integration Flows: Generated bean names

Starting with _version 5.0.5_, generated bean names for the components in an `IntegrationFlow` include the flow bean name, followed by a dot, as a prefix.

See <<java-dsl-flows>> for more information.

==== Aggregator Changes

An aggregator now expires the group immediately, if the `groupTimeout` is evaluated to a negative value.
Only `null` is considered as a signal do nothing for the current message.

See <<aggregator>> for more information.

==== @Publisher annotation changes

Starting with _version 5.1, the `@Publisher` AOP functionality has to be turned on explicitly via `@EnablePublisher` or via `<int:enable-publisher>` sub-element on the `<int:annotation-config>`.

See <<publisher-annotation>> for more information.

=== AMQP Changes

`ID` and `Timestamp` header mapping changes in the `DefaultAmqpHeaderMapper`.
See the note near the bottom of <<amqp-message-headers>> for more information.

The `contentType` header is no longer incorrectly mapped as an entry in the general headers map.
See <<amqp-content-type>> for more information.

=== JDBC Changes

A confusing `max-rows-per-poll` property on the JDBC Inbound Channel Adapter and JDBC Outbound Gateway has been deprecated in favor newly introduced `max-rows` property.

See <<jdbc>> for more information.
