[[whats-new]]
== What's new in Spring Integration 5.0?

This chapter provides an overview of the new features and improvements that have been introduced with Spring
Integration 5.0.
If you are interested in more details, please see the Issue Tracker tickets that were resolved as part of the 5.0
development process.

[[x5.0-new-components]]
=== New Components


[[x5.0-general]]
=== General Changes

==== Core Changes

==== JMS Changes

Previously, Spring Integration used a default bean name `connectionFactory` for the JMS Connection Factory, allowing the property to be omitted from component definitions.

Spring Boot auto-configures a bean name `jmsConnectionFactory`.

Since it is common to use Spring Integration XML configuration with Spring Boot, it was decided that it would be useful to align the two so that an SI app can use the auto configured bean.

If your application is relying on the previous behavior, rename your `connectionFactory` bean to `jmsConnectionFactory`, or specifically configure your components to use your bean using its current name.
