description = 'Spring Integration JDBC Support'
dependencies {
	api 'org.springframework:spring-jdbc'
	optionalApi libs.org.postgresql

	testImplementation libs.com.h2database.h2
	testImplementation libs.org.hsqldb
	testImplementation libs.apache.derby
	testImplementation libs.apache.derbytools
	testImplementation libs.apache.derbyclient
	testImplementation libs.org.postgresql
	testImplementation libs.apache.commons.dbcp2
	testImplementation 'org.testcontainers:testcontainers-mysql'
	testImplementation 'org.testcontainers:testcontainers-postgresql'
	testImplementation 'org.testcontainers:testcontainers-oracle-xe'
	testImplementation 'tools.jackson.core:jackson-databind'

	testRuntimeOnly libs.com.oracle.ojdbc11
	testRuntimeOnly libs.com.mysql.connector
}
