CREATE TABLE INT_MESSAGE  (
	MESSAGE_ID VARCHAR(100) NOT NULL PRIMARY KEY,
	REGION VARCHAR(100),
	CREATED_DATE TIMESTAMP NOT NULL,
	MESSAGE_BYTES BLOB
);

CREATE TABLE INT_MESSAGE_GROUP  (
	MESSAGE_ID VARCHAR(100) NOT NULL,
	CORRELATION_KEY VARCHAR(100) NOT NULL,
	REGION VARCHAR(100),
	MARKED INTEGER,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP,
	MESSAGE_BYTES BLOB,
	constraint MESSAGE_GROUP_PK primary key (MESSAGE_ID, CORRELATION_KEY)
);


