DROP TABLE IF EXISTS JSON_CHANNEL_MESSAGE;

CREATE TABLE JSON_CHANNEL_MESSAGE  (
    MESSAGE_ID       CHAR(36)     NOT NULL,
    GROUP_KEY        CHAR(36)     NOT NULL,
    CREATED_DATE     BIGINT       NOT NULL,
    MESSAGE_PRIORITY BIGINT,
    MESSAGE_SEQUENCE BIGINT       NOT NULL AUTO_INCREMENT UNIQUE,
    MESSAGE_CONTENT    JSON,
    REGION           VARCHAR(100) NOT NULL,
    constraint JSON_CHANNEL_MESSAGE_PK primary key (REGION, GROUP_KEY, CREATED_DATE, MESSAGE_SEQUENCE)
) ENGINE=InnoDB;

CREATE INDEX JSON_CHANNEL_MSG_DELETE_IDX ON JSON_CHANNEL_MESSAGE (REGION, GROUP_KEY, MESSAGE_ID);
