DROP TABLE IF EXISTS JSON_CHANNEL_MESSAGE CASCADE;
DROP SEQUENCE IF EXISTS JSON_MESSAGE_SEQ;

CREATE SEQUENCE JSON_MESSAGE_SEQ START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE TABLE JSON_CHANNEL_MESSAGE  (
    MESSAGE_ID       CHAR(36)     NOT NULL,
    GROUP_KEY        CHAR(36)     NOT NULL,
    CREATED_DATE     BIGINT       NOT NULL,
    MESSAGE_PRIORITY BIGINT,
    MESSAGE_SEQUENCE BIGINT       NOT NULL DEFAULT nextval('JSON_MESSAGE_SEQ'),
    MESSAGE_CONTENT  JSONB,
    REGION           VARCHAR(100) NOT NULL,
    constraint JSON_CHANNEL_MESSAGE_PK primary key (REGION, GROUP_KEY, CREATED_DATE, MESSAGE_SEQUENCE)
);

CREATE INDEX JSON_CHANNEL_MSG_DELETE_IDX ON JSON_CHANNEL_MESSAGE (REGION, GROUP_KEY, MESSAGE_ID);
