/*
 * Copyright 2002-present the original author or authors.
 */

package org.springframework.integration.channel.config;

import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.integration.channel.DirectChannel;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * @author Mark Fisher
 * @author Artem Bilan
 */
@SpringJUnitConfig
@DirtiesContext
public class AutoGeneratedChannelTests {

	@Autowired
	private ApplicationContext context;

	@Test
	public void checkConfig() {
		Object input = context.getBean("input");
		assertThat(input).isNotNull();
		assertThat(input.getClass()).isEqualTo(DirectChannel.class);
	}

}
