/*
 * Copyright 2015-present the original author or authors.
 */

package org.springframework.integration.stomp.event;

import org.jspecify.annotations.Nullable;

import org.springframework.integration.events.IntegrationEvent;

/**
 * Base class for all {@link IntegrationEvent}s generated by the STOMP Adapters.
 *
 * @author Artem Bilan
 * @author Gary Russell
 *
 * @since 4.2
 */
@SuppressWarnings("serial")
public abstract class StompIntegrationEvent extends IntegrationEvent {

	public StompIntegrationEvent(Object source) {
		super(source);
	}

	public StompIntegrationEvent(Object source, @Nullable Throwable cause) {
		super(source, cause);
	}

}
