/*
 * Copyright © 2013 Broadcom Inc. and/or its subsidiaries. All Rights Reserved.
 * Copyright 2013-present the original author or authors.
 */

package org.springframework.integration.events;

import org.springframework.context.ApplicationEvent;
import org.springframework.lang.Nullable;

/**
 * Base class for all {@link ApplicationEvent}s generated by the framework.
 * Contains an optional cause field; a separate Exception event hierarchy
 * is not possible because of Java single inheritance (modules should make
 * all their events subclasses of 'xxxIntegrationEvent').
 *
 * @author Gary Russell
 * @since 3.0
 *
 */
@SuppressWarnings("serial")
public abstract class IntegrationEvent extends ApplicationEvent {

	protected final Throwable cause; // NOSONAR protected final

	public IntegrationEvent(Object source) {
		this(source, null);
	}

	public IntegrationEvent(Object source, @Nullable Throwable cause) {
		super(source);
		this.cause = cause;
	}

	@Nullable
	public Throwable getCause() {
		return this.cause;
	}

	/**
	 * Get the source as a specific type; the receiving variable must be declared with the
	 * correct type.
	 * @param <T> the type.
	 * @return the source.
	 * @since 5.4
	 */
	@SuppressWarnings("unchecked")
	public <T> T getSourceAsType() {
		return (T) getSource();
	}

	@Override
	public String toString() {
		return this.getClass().getSimpleName() + " [source=" + this.getSource() +
				(this.cause == null ? "" : ", cause=" + this.cause) + "]";
	}

}
