// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoTest.proto

package org.springframework.integration.transformer.proto;

public interface TestClass2OrBuilder extends
		// @@protoc_insertion_point(interface_extends:tutorial.TestClass2)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>optional string bar = 1;</code>
	 * @return Whether the bar field is set.
	 */
	boolean hasBar();
	/**
	 * <code>optional string bar = 1;</code>
	 * @return The bar.
	 */
	java.lang.String getBar();
	/**
	 * <code>optional string bar = 1;</code>
	 * @return The bytes for bar.
	 */
	com.google.protobuf.ByteString
			getBarBytes();

	/**
	 * <code>optional int32 qux = 2;</code>
	 * @return Whether the qux field is set.
	 */
	boolean hasQux();
	/**
	 * <code>optional int32 qux = 2;</code>
	 * @return The qux.
	 */
	int getQux();
}
