// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoTest.proto

package org.springframework.integration.transformer.proto;

public final class TestProtos {
	private TestProtos() {}
	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
				(com.google.protobuf.ExtensionRegistryLite) registry);
	}
	static final com.google.protobuf.Descriptors.Descriptor
		internal_static_tutorial_TestClass1_descriptor;
	static final
		com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_tutorial_TestClass1_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor
		internal_static_tutorial_TestClass2_descriptor;
	static final
		com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_tutorial_TestClass2_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
			getDescriptor() {
		return descriptor;
	}
	private static  com.google.protobuf.Descriptors.FileDescriptor
			descriptor;
	static {
		java.lang.String[] descriptorData = {
			"\n\017ProtoTest.proto\022\010tutorial\"&\n\nTestClass" +
			"1\022\013\n\003bar\030\001 \001(\t\022\013\n\003qux\030\002 \001(\005\"&\n\nTestClass" +
			"2\022\013\n\003bar\030\001 \001(\t\022\013\n\003qux\030\002 \001(\005BA\n1org.sprin" +
			"gframework.integration.transformer.proto" +
			"B\nTestProtosP\001"
		};
		descriptor = com.google.protobuf.Descriptors.FileDescriptor
			.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {
				});
		internal_static_tutorial_TestClass1_descriptor =
			getDescriptor().getMessageTypes().get(0);
		internal_static_tutorial_TestClass1_fieldAccessorTable = new
			com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_tutorial_TestClass1_descriptor,
				new java.lang.String[] { "Bar", "Qux", });
		internal_static_tutorial_TestClass2_descriptor =
			getDescriptor().getMessageTypes().get(1);
		internal_static_tutorial_TestClass2_fieldAccessorTable = new
			com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_tutorial_TestClass2_descriptor,
				new java.lang.String[] { "Bar", "Qux", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
