[[cloudevents]]
= CloudEvents Support

Spring Integration provides transformers (starting with version 7.1) for transforming messages into CloudEvent messages.
It is fully based on the https://github.com/cloudevents/sdk-java[CloudEvents SDK] project.

Add the following dependency to your project:

[tabs]
======
Maven::
+
[source, xml, subs="normal", role="primary"]
----
<dependency>
    <groupId>org.springframework.integration</groupId>
    <artifactId>spring-integration-cloudevents</artifactId>
    <version>{project-version}</version>
</dependency>
----

Gradle::
+
[source, groovy, subs="normal", role="secondary"]
----
compile "org.springframework.integration:spring-integration-cloudevents:{project-version}"
----
======

[[to-cloud-event-transformer]]

=== `ToCloudEventTransformer`

The `ToCloudEventTransformer` converts Spring Integration messages into CloudEvents compliant messages.
This transformer provides support for the CloudEvents specification v1.0 with configurable output format and defining attributes using ``Expression`` s and identifying extensions in the message headers via patterns.

NOTE: Ensure messages to be transformed have a payload of type `byte[]`.
The transformer throws an `IllegalArgumentException` if the payload is not a byte array.

==== Attribute Expressions

Set the CloudEvents' attributes of `id`, `source`, `type`, `dataSchema`, and `subject` through SpEL ``Expression``s.

NOTE: The `time` attribute is set to the time that the CloudEvent message was created by the `ToCloudEventTransformer` transformer.

The following table contains the attribute names and the values returned by the default ``Expression``s.

|===
| Attribute Name | Default Value

| `id`
| The id of the message.

| `source`
| Prefix of "/spring/" followed by the appName, a period, and then the name of the transformer's bean (for example, `/spring/myapp.toCloudEventTransformerBean`).

| `type`
| "spring.message"

| `dataContentType`
| The contentType of the message, defaults to `application/octet-stream`.
Some other examples are but not limited to: `application/json`, `application/x-avro`, and `application/xml`.

| `dataSchema`
| `null`

| `subject`
| `null`

| `time`
| The time the CloudEvent message is created.
|===

==== Extension Patterns

The extensionPatterns constructor parameter is a vararg of ``String``s.
Each `pattern` in the array is the search criteria for finding the headers that need to be added as extensions to the new `CloudEvent`.
In this example, the following patterns were passed to the constructor: `"trace*", "span-id", "user-id"`.
`ToCloudEventTransformer` searches for any header key that starts with the word `trace` and adds those headers to the extensions for the `CloudEvent` message.
Then it searches for any header that contains a key of `span-id` as well as `user-id` and adds those headers as extensions if found.

[[configuration-with-dsl]]
==== Configuration With DSL

Add the CloudEvent transformer to flows using the DSL:

[source,java]
----
@Bean
public ToCloudEventTransformer cloudEventTransformer() {
    return new ToCloudEventTransformer();
}

@Bean
public IntegrationFlow cloudEventTransformFlow(ToCloudEventTransformer toCloudEventTransformer) {
    return IntegrationFlows
        .from("inputChannel")
        .transform(toCloudEventTransformer)
        .channel("outputChannel")
        .get();
}
----

[[cloudevent-transformer-process]]
==== CloudEvent Transformer Process

The transformer follows the process below:

1. **CloudEvent Building**: Builds CloudEvent attributes.
2. **Extension Extraction**: Builds the CloudEvent extensions using the array of extensionPatterns passed into the constructor.
3. **Format Conversion**: Applies the specified `EventFormat` based on the message's `contentType` to create the CloudEvent.

A basic transformation may have the following pattern:

[source,java]
----
// Input message with headers
Message<byte[]> inputMessage = MessageBuilder
    .withPayload("Hello CloudEvents".getBytes(StandardCharsets.UTF_8))
    .withHeader(MessageHeaders.CONTENT_TYPE, "application/octet-stream")
    .build();
// Transformer with extension patterns
ToCloudEventTransformer transformer = new ToCloudEventTransformer();

// Transform to CloudEvent
Object cloudEventMessage = transformer.transform(inputMessage);
----

[[eventformats]]
==== EventFormats

The `ToCloudEventTransformer` uses ``EventFormat``s to serialize the CloudEvent into the message's payload.
To utilize a specific `EventFormat`, add the associated dependency.
For example, to add the XML `EventFormat`, add the following dependency: `io.cloudevents:cloudevents-xml`.
See the https://github.com/cloudevents/sdk-java[CloudEvents SDK project's] reference docs for information on the ``EventFormat``s that are available.
