[[cloudevents-transformer]]

= CloudEvent Transformer

[[introduction]]
== Introduction

The CloudEvent transformer converts Spring Integration messages into CloudEvent compliant messages.
This transformer provides  support for the CloudEvents specification v1.0 with configurable output format and defining attributes and extensions using `Expression`s.

[[cloudevent-transformer-overview]]
=== Overview

The CloudEvent transformer (`ToCloudEventTransformer`) extends Spring Integration's `AbstractTransformer` to convert messages to CloudEvent format.
The CloudEvent transformer identifies the `EventFormat` classes in the classpath and utilizes registers these as the available serializers for CloudEvents.
The type of serialization (JSON, XML, AVRO, etc) of the CloudEvent message is determined by `contentType` of the message.

NOTE: Messages to be transformed must have a payload of `byte[]`.



[[configure-transformer]]
=== Configuring Transformer

The `ToCloudEventTransformer` allows the user to use SpEL `Expression`s to populate the attributes as well as the extensions.

==== Attribute Expressions
As discussed above users are allowed to set the `id`, `source`, `type`, `dataSchema`, `subject` through SpEL `Expression`s.
The example below shows where a `ToCloudEventTransformer` is created with a null `expression`s variable.
This indicates that this transformer will not place any `extensions` in the CloudEvent.
But the user does want to set the type of the CloudEvent to `sampleType`.

NOTE: The `time` attribute is set to the time that the CloudEvent message was created by the `ToCloudEventTransformer` transformer.

[source,java]
----
ExpressionParser parser = new SpelExpressionParser();
ToCloudEventTransformer transformer = new ToCloudEventTransformer(null);
transformer.setTypeExpression(parser.parseExpression("sampleType"));
----

==== Extension Expressions
The expressions constructor parameter is an array of `Expression`s.
If the array is null, then no extensions will be added to the CloudEvent.
Each `Expression` in the array must return the type Map<String, Object>.
Where the key is a string and the value is of type object.
In the example below the extensions are hard coded to return 3 `Map<String, Object>` objects each containing one extension.
[source,java]
----
ExpressionParser parser = new SpelExpressionParser();
Expression[] extensionExpressions = {
		parser.parseExpression("{'trace-id' : 'trace-123'}"),
        parser.parseExpression("{'span-id' : 'span-456'}"),
        parser.parseExpression("{'user-id' : 'user-789'}")};
return new ToCloudEventTransformer(extensionExpressions);
----

[[cloudevent-attribute-defaults]]
==== Default Values
The following table contains the Attribute names and the value returned by the default `Expression`s.

|===
| Attribute Name | Default Value

| `id`
| the id of the message.

| `source`
| Prefix of "/spring/" followed by the appName a `.` then the name of the transformer's bean.

| `type`
| "spring.message"

| `dataContentType`
| The `contentType` of the message.

| `dataSchema`
| `null`

| `subject`
| `null`

| `time`
| The time the CloudEvent message is created
|===

[[cloudevent-transformer-integration]]
=== Integration with Spring Integration Flows

The CloudEvent transformer integrates with Spring Integration flows:

==== Basic Flow

[source,java]
----
@Bean
public IntegrationFlow cloudEventTransformFlow() {
    return IntegrationFlows
        .from("inputChannel")
        .transform(cloudEventTransformer())
        .channel("outputChannel")
        .get();
}
----

[[cloudevent-transformer-transformation-process]]
=== Transformation Process

The transformer follows the process below:

1. **CloudEvent Building**: Build CloudEvent attributes
2. **Extension Extraction**: Build the CloudEvent extensions using the array of extensionExpressions passed into the constructor.
3. **Format Conversion**: Apply the specified `EventFormat` based on the message's `contentType to create the CloudEvent.

[[cloudevent-transformer-examples]]
=== Examples

[[cloudevent-transformer-example-basic]]
==== Basic Message Transformation

[source,java]
----
// Input message with headers
Message<String> inputMessage = MessageBuilder
    .withPayload("Hello CloudEvents")
    .build();
// Transformer with extension patterns
ToCloudEventTransformer transformer = new ToCloudEventTransformer();

// Transform to CloudEvent
Object cloudEventMessage = transformer.transform(inputMessage);
----

