[[cloudevents]]
= CloudEvents Support

Spring Integration provides transformers (starting with version 7.1) for transforming messages into CloudEvent messages.
It is fully based on the https://github.com/cloudevents/sdk-java[CloudEvents SDK] project.

This dependency is required for the project:

[tabs]
======
Maven::
+
[source, xml, subs="normal", role="primary"]
----
<dependency>
    <groupId>org.springframework.integration</groupId>
    <artifactId>spring-integration-cloudevents</artifactId>
    <version>{project-version}</version>
</dependency>
----

Gradle::
+
[source, groovy, subs="normal", role="secondary"]
----
compile "org.springframework.integration:spring-integration-cloudevents:{project-version}"
----
======

[[to-cloud-event-transformer]]
=== ToCloudEventTransformer

The `ToCloudEventTransformer` converts Spring Integration messages into CloudEvents compliant messages.
This transformer provides support for the CloudEvents specification v1.0 with configurable output format and defining attributes using ``Expression`` s and identifying extensions in the message headers via patterns.

NOTE: Messages to be transformed must have a payload of type `byte[]`.
The transformer will throw an `IllegalArgumentException` if the payload is not a byte array.

==== Attribute Expressions
Users are allowed to set the CloudEvents' attributes of `id`, `source`, `type`, `dataSchema`, `subject` through SpEL ``Expression``s.

NOTE: The `time` attribute is set to the time that the CloudEvent message was created by the `ToCloudEventTransformer` transformer.

The following table contains the Attribute names and the value returned by the default ``Expression``s.

|===
| Attribute Name | Default Value

| `id`
| the id of the message.

| `source`
| prefix of "/spring/" followed by the appName a period then the name of the transformer's bean. i.e. `/spring/myapp.toCloudEventTransformerBean`

| `type`
| "spring.message"

| `dataContentType`
| The contentType of the message, defaults to "application/octet-stream"

| `dataSchema`
| `null`

| `subject`
| `null`

| `time`
| the time the CloudEvent message is created
|===

==== Extension Patterns

The extensionPatterns constructor parameter is a Vararg of ``String``s.
Each `pattern` in the array is the search criteria for finding the headers that need to be added as extensions to the new `CloudEvent`.
In this example the following patterns were passed to the constructor: `"trace*", "span-id", "user-id"`.  `ToCloudEventTransformer` will search for any header key that starts with the word `trace` and add those headers to the extensions for the `CloudEvent` message.
Then it will search for any header that contains a key of `span-id` as well as `user-id` and add those headers as extensions if found.

[[cloudevent-transformer-integration]]
==== Integration with Spring Integration Flows

The CloudEvent transformer integrates with Spring Integration flows:

[source,java]
----
@Bean
public ToCloudEventTransformer cloudEventTransformer() {
    return new ToCloudEventTransformer();
}

@Bean
public IntegrationFlow cloudEventTransformFlow(ToCloudEventTransformer toCloudEventTransformer) {
    return IntegrationFlows
        .from("inputChannel")
        .transform(toCloudEventTransformer)
        .channel("outputChannel")
        .get();
}
----

[[cloudevent-transformer-process]]
==== CloudEvent Transformer Process

The transformer follows the process below:

1. **CloudEvent Building**: Build CloudEvent attributes
2. **Extension Extraction**: Build the CloudEvent extensions using the array of extensionPatterns passed into the constructor.
3. **Format Conversion**: Apply the specified `EventFormat` based on the message's `contentType` to create the CloudEvent.

A basic transformation may have the following pattern:

[source,java]
----
// Input message with headers
Message<byte[]> inputMessage = MessageBuilder
    .withPayload("Hello CloudEvents".getBytes(StandardCharsets.UTF_8))
    .withHeader(MessageHeaders.CONTENT_TYPE, "application/octet-stream")
    .build();
// Transformer with extension patterns
ToCloudEventTransformer transformer = new ToCloudEventTransformer();

// Transform to CloudEvent
Object cloudEventMessage = transformer.transform(inputMessage);
----

[[eventformats]]
==== EventFormats

The `ToCloudEventTransformer` uses ``EventFormat``s to serialize the CloudEvent into the message's payload. To utilize a specific `EventFormat` the associated dependency needs to be added. For example adding the XML `EventFormat` would require the following dependency `io.cloudevents:cloudevents-xml`.
Information on the ``EventFormat``s that are available can be found in the https://github.com/cloudevents/sdk-java[CloudEvents SDK project's] reference docs.
