[[whats-new-part]]
= What's New?

[[spring-integration-intro-new]]
For those who are already familiar with Spring Integration, this chapter provides a brief overview of the new features of version 7.2.

If you are interested in the changes and features that were introduced in earlier versions, see the xref:history.adoc[Change History].

[[what-s-new-in-spring-integration-7-2]]
== What's New in Spring Integration 7.2?

For more details, see the https://github.com/spring-projects/spring-integration/issues[GitHub Issues] that were resolved as part of the 7.2 development process.

In general, the project has been moved to the latest dependency versions.
Java 17 is still the baseline, but Java 25 is supported.

[[x7.2-new-components]]
=== New Components

[[x7.2-general-changes]]
=== General Changes

The `DefaultErrorMessageStrategy` now preserves the original headers when building the `ErrorMessage`.
See xref:error-handling.adoc[] for more information.

[[x7.2-amqp-changes]]
=== AMQP Support Changes

The `wait-for-confirm` option on the outbound channel adapter now also works with simple publisher confirms.
When the message has no correlation data, the send is performed within the scope of a `RabbitTemplate.invoke()` operation and `waitForConfirmsOrDie()` is used.
A warning is now logged when the option is set but the connection factory supports no publisher confirms at all.
See xref:amqp/outbound-channel-adapter.adoc[] for more information.
