[[whats-new-part]]
= What's New?

[[spring-integration-intro-new]]
For those who are already familiar with Spring Integration, this chapter provides a brief overview of the new features of version 7.1.

If you are interested in the changes and features that were introduced in earlier versions, see the xref:history.adoc[Change History].

[[what-s-new-in-spring-integration-7-1]]
== What's New in Spring Integration 7.1?

For more details, see the https://github.com/spring-projects/spring-integration/issues[GitHub Issues] that were resolved as part of the 7.1 development process.

In general, the project has been moved to the latest dependency versions.
Java 17 is still the baseline, but Java 25 is supported.

[[x7.0-web-services-changes]]
=== Web Services Support Changes

The Web Services Outbound Gateway now can rely on the provided `WebServiceTemplate.defaultUri`.
See xref:ws.adoc[] for more information.

[[x7.1-cloudevents]]
=== CloudEvents

The new `spring-integration-cloudevents` module has been introduced to support CloudEvents specification.
See xref:cloudevents.adoc[] for more information.
