[[whats-new-part]]
= What's New?

[[spring-integration-intro-new]]
For those who are already familiar with Spring Integration, this chapter provides a brief overview of the new features of version 7.0.

If you are interested in the changes and features that were introduced in earlier versions, see the xref:history.adoc[Change History].

[[what-s-new-in-spring-integration-7-0]]
== What's New in Spring Integration 7.0?

For more details, see the https://github.com/spring-projects/spring-integration/issues[GitHub Issues] that were resolved as part of the 7.0 development process.

In general the project has been moved to the latest dependency versions.
Java 17 is still baseline, but Java 24 is supported.

[[x7.0-general]]
== General Changes

Junit 4 Based Support Components are deprecated.

[[x7.0-new-components]]
== New Components

A new `DistributedLock` interface has been introduced, providing new methods, `lock(Duration ttl`) and `tryLock(long time, TimeUnit unit, Duration ttl)`, to acquire a lock with a custom time-to-live (TTL).
See xref:distributed-locks.adoc[] for more information.

[[x7.0-jdbc-changes]]
=== JDBC Changes

The JDBC module now provides a Java DSL API via its dedicated `org.springframework.integration.jdbc.dsl.Jdbc` factory.
The xref:jdbc/dsl.adoc[] chapter provides more details.

The `JdbcLock` now supports the feature of customized time-to-live for the lock status data.
See xref:jdbc/lock-registry.adoc[] for more information.

[[x7.0-redis-changes]]
=== Redis Changes

The `RedisLock` now supports the feature of customized time-to-live for the lock status data.
See xref:redis.adoc#redis-lock-registry[Redis Lock Registry] for more information.

[[x7.0-hazelcast-changes]]
=== Hazelcast Changes

Previously deprecated classes in the `spring-integation-hazelcast` module, such as `LeaderInitiator`, `HazelcastMembershipListener`, `HazelcastLocalInstanceRegistrar` and `HazelcastLockRegistry`, are now removed due to not supported CP-subsystem in Hazelcast library for Open Source.

[[x7.0-mqtt-changes]]
=== MQTT Changes

The `AbstractMqttMessageDrivenChannelAdapter` and `ClientManager` implementations now expose a `quiescentTimeout` option which is propagated in their `stop()` method down to the `disconnectForcibly()` API of the MQTT Paho clients.
See xref:mqtt.adoc[] for more information.