name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - '*.x'

concurrency:
  group: group-ci-for-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        testJavaVersion: [ 17, 21, 26 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    uses: spring-io/spring-github-workflows/.github/workflows/spring-gradle-ci.yml@main
    with:
      testJavaVersion: ${{ matrix.testJavaVersion }}
      runner: ${{ matrix.os }}
    secrets:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
