name: Merge Dependabot PR

on:
  pull_request:
    branches:
      - main
      - '*.x'

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:
    permissions: write-all

    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@v4
    with:
      mergeArguments: --auto --squash
      autoMergeSnapshots: true